INSERT IGNORE INTO brands (name) VALUES
('Alfa Romeo'),
('Alpine'),
('Aston Martin'),
('Audi'),
('Autosan'),
('Bentley'),
('BMW'),
('Bugatti'),
('Cadillac'),
('Chevrolet'),
('Chrysler'),
('Citroen'),
('Dacia'),
('Daewoo'),
('DAF'),
('De Tomaso'),
('Dodge'),
('Ducati'),
('Ferrari'),
('Fiat'),
('Ford'),
('Harley-Davidson'),
('Honda'),
('Hummer'),
('Hyundai'),
('Ikarus'),
('Isuzu'),
('Iveco'),
('Jaguar'),
('Jawa'),
('Jelcz'),
('Jeep'),
('Karosa'),
('Kawasaki'),
('Kia'),
('KTM'),
('Lada'),
('Lamborghini'),
('Lancia'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Lublin'),
('MAN'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes'),
('MG'),
('Mini'),
('Mitsubishi'),
('Moto Guzzi'),
('Neoplan'),
('Nissan'),
('Opel'),
('Peugeot'),
('Polski Fiat'),
('Porsche'),
('Renault'),
('Rolls-Royce'),
('Rover'),
('Saab'),
('Scania'),
('Seat'),
('Setra'),
('SHL'),
('Simson'),
('Skoda'),
('Smart'),
('Solaris'),
('Star'),
('Subaru'),
('Suzuki'),
('Syrena'),
('Tatra'),
('Tesla'),
('Toyota'),
('Trabant'),
('Triumph'),
('Ursus'),
('Volkswagen'),
('Volvo'),
('Wartburg'),
('WSK'),
('Yamaha'),
('Zastava');

-- ============================================================
-- MODELS (grouped by brand)
-- ============================================================

-- Alfa Romeo
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Giulia'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Stelvio'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Tonale'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '156'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '159'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '147'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '146'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '145'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'GT'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Brera'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Spider'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Giulietta'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'Mito'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '33'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '75'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '164'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), '166'),
((SELECT id FROM brands WHERE name='Alfa Romeo'), 'GTV');

-- Alpine
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Alpine'), 'A110'),
((SELECT id FROM brands WHERE name='Alpine'), 'A310'),
((SELECT id FROM brands WHERE name='Alpine'), 'A610');

-- Aston Martin
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Aston Martin'), 'DB5'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'DB9'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'DBS'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'Vantage'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'DB11'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'DBX'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'Vanquish'),
((SELECT id FROM brands WHERE name='Aston Martin'), 'Valhalla');

-- Audi
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Audi'), '80 B4'),
((SELECT id FROM brands WHERE name='Audi'), '100 C4'),
((SELECT id FROM brands WHERE name='Audi'), 'A3'),
((SELECT id FROM brands WHERE name='Audi'), 'A4 B5'),
((SELECT id FROM brands WHERE name='Audi'), 'A4 B6'),
((SELECT id FROM brands WHERE name='Audi'), 'A4 B7'),
((SELECT id FROM brands WHERE name='Audi'), 'A4 B8'),
((SELECT id FROM brands WHERE name='Audi'), 'A4 B9'),
((SELECT id FROM brands WHERE name='Audi'), 'A5'),
((SELECT id FROM brands WHERE name='Audi'), 'A6 C4'),
((SELECT id FROM brands WHERE name='Audi'), 'A6 C5'),
((SELECT id FROM brands WHERE name='Audi'), 'A6 C6'),
((SELECT id FROM brands WHERE name='Audi'), 'A6 C7'),
((SELECT id FROM brands WHERE name='Audi'), 'A6 C8'),
((SELECT id FROM brands WHERE name='Audi'), 'A7'),
((SELECT id FROM brands WHERE name='Audi'), 'A8'),
((SELECT id FROM brands WHERE name='Audi'), 'Q3'),
((SELECT id FROM brands WHERE name='Audi'), 'Q5'),
((SELECT id FROM brands WHERE name='Audi'), 'Q7'),
((SELECT id FROM brands WHERE name='Audi'), 'Q8'),
((SELECT id FROM brands WHERE name='Audi'), 'TT'),
((SELECT id FROM brands WHERE name='Audi'), 'R8'),
((SELECT id FROM brands WHERE name='Audi'), 'e-tron'),
((SELECT id FROM brands WHERE name='Audi'), 'S3'),
((SELECT id FROM brands WHERE name='Audi'), 'S4'),
((SELECT id FROM brands WHERE name='Audi'), 'RS6'),
((SELECT id FROM brands WHERE name='Audi'), 'RS4'),
((SELECT id FROM brands WHERE name='Audi'), 'Coupe'),
((SELECT id FROM brands WHERE name='Audi'), 'Cabriolet'),
((SELECT id FROM brands WHERE name='Audi'), 'V8');

-- Autosan
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Autosan'), 'H9'),
((SELECT id FROM brands WHERE name='Autosan'), 'A1010M'),
((SELECT id FROM brands WHERE name='Autosan'), 'M12'),
((SELECT id FROM brands WHERE name='Autosan'), 'Sancity 12'),
((SELECT id FROM brands WHERE name='Autosan'), 'Gemini'),
((SELECT id FROM brands WHERE name='Autosan'), 'Eurolider'),
((SELECT id FROM brands WHERE name='Autosan'), 'Lider 9');

-- Bentley
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Bentley'), 'Continental GT'),
((SELECT id FROM brands WHERE name='Bentley'), 'Flying Spur'),
((SELECT id FROM brands WHERE name='Bentley'), 'Bentayga'),
((SELECT id FROM brands WHERE name='Bentley'), 'Mulsanne'),
((SELECT id FROM brands WHERE name='Bentley'), 'Turbo R'),
((SELECT id FROM brands WHERE name='Bentley'), 'Azure');

-- BMW
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='BMW'), 'E30'),
((SELECT id FROM brands WHERE name='BMW'), 'E34'),
((SELECT id FROM brands WHERE name='BMW'), 'E36'),
((SELECT id FROM brands WHERE name='BMW'), 'E38'),
((SELECT id FROM brands WHERE name='BMW'), 'E39'),
((SELECT id FROM brands WHERE name='BMW'), 'E46'),
((SELECT id FROM brands WHERE name='BMW'), 'E60'),
((SELECT id FROM brands WHERE name='BMW'), 'E65'),
((SELECT id FROM brands WHERE name='BMW'), 'E87'),
((SELECT id FROM brands WHERE name='BMW'), 'E90'),
((SELECT id FROM brands WHERE name='BMW'), 'E91'),
((SELECT id FROM brands WHERE name='BMW'), 'E92'),
((SELECT id FROM brands WHERE name='BMW'), 'E93'),
((SELECT id FROM brands WHERE name='BMW'), 'F10'),
((SELECT id FROM brands WHERE name='BMW'), 'F20'),
((SELECT id FROM brands WHERE name='BMW'), 'F30'),
((SELECT id FROM brands WHERE name='BMW'), 'F32'),
((SELECT id FROM brands WHERE name='BMW'), 'G20'),
((SELECT id FROM brands WHERE name='BMW'), 'G30'),
((SELECT id FROM brands WHERE name='BMW'), 'G31'),
((SELECT id FROM brands WHERE name='BMW'), 'G80'),
((SELECT id FROM brands WHERE name='BMW'), 'X1'),
((SELECT id FROM brands WHERE name='BMW'), 'X3'),
((SELECT id FROM brands WHERE name='BMW'), 'X5'),
((SELECT id FROM brands WHERE name='BMW'), 'X6'),
((SELECT id FROM brands WHERE name='BMW'), 'X7'),
((SELECT id FROM brands WHERE name='BMW'), 'Z3'),
((SELECT id FROM brands WHERE name='BMW'), 'Z4'),
((SELECT id FROM brands WHERE name='BMW'), 'i3'),
((SELECT id FROM brands WHERE name='BMW'), 'i4'),
((SELECT id FROM brands WHERE name='BMW'), 'i8'),
((SELECT id FROM brands WHERE name='BMW'), 'iX'),
((SELECT id FROM brands WHERE name='BMW'), 'M3'),
((SELECT id FROM brands WHERE name='BMW'), 'M5'),
((SELECT id FROM brands WHERE name='BMW'), 'M6'),
((SELECT id FROM brands WHERE name='BMW'), 'R 1250 GS'),
((SELECT id FROM brands WHERE name='BMW'), 'R 1200 GS'),
((SELECT id FROM brands WHERE name='BMW'), 'S 1000 RR'),
((SELECT id FROM brands WHERE name='BMW'), 'K 1600 GTL'),
((SELECT id FROM brands WHERE name='BMW'), 'F 800 GS');

-- Bugatti
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Bugatti'), 'Veyron'),
((SELECT id FROM brands WHERE name='Bugatti'), 'Chiron'),
((SELECT id FROM brands WHERE name='Bugatti'), 'Divo'),
((SELECT id FROM brands WHERE name='Bugatti'), 'EB 110'),
((SELECT id FROM brands WHERE name='Bugatti'), 'Mistral');

-- Cadillac
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Cadillac'), 'Escalade'),
((SELECT id FROM brands WHERE name='Cadillac'), 'CTS'),
((SELECT id FROM brands WHERE name='Cadillac'), 'DeVille'),
((SELECT id FROM brands WHERE name='Cadillac'), 'Eldorado'),
((SELECT id FROM brands WHERE name='Cadillac'), 'Seville'),
((SELECT id FROM brands WHERE name='Cadillac'), 'SRX'),
((SELECT id FROM brands WHERE name='Cadillac'), 'XT5');

-- Chevrolet
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Chevrolet'), 'Camaro'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Corvette'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Malibu'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Cruze'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Spark'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Aveo'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Epica'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Lacetti'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Tahoe'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Suburban'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Silverado'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Blazer'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'TrailBlazer'),
((SELECT id FROM brands WHERE name='Chevrolet'), 'Volt');

-- Chrysler
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Chrysler'), '300C'),
((SELECT id FROM brands WHERE name='Chrysler'), 'PT Cruiser'),
((SELECT id FROM brands WHERE name='Chrysler'), 'Grand Voyager'),
((SELECT id FROM brands WHERE name='Chrysler'), 'Neon'),
((SELECT id FROM brands WHERE name='Chrysler'), 'Sebring'),
((SELECT id FROM brands WHERE name='Chrysler'), 'Crossfire'),
((SELECT id FROM brands WHERE name='Chrysler'), 'Voyager');

-- Citroen
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Citroen'), 'ZX'),
((SELECT id FROM brands WHERE name='Citroen'), 'AX'),
((SELECT id FROM brands WHERE name='Citroen'), 'BX'),
((SELECT id FROM brands WHERE name='Citroen'), 'C1'),
((SELECT id FROM brands WHERE name='Citroen'), 'C2'),
((SELECT id FROM brands WHERE name='Citroen'), 'C3'),
((SELECT id FROM brands WHERE name='Citroen'), 'C3 III'),
((SELECT id FROM brands WHERE name='Citroen'), 'C4'),
((SELECT id FROM brands WHERE name='Citroen'), 'C4 Cactus'),
((SELECT id FROM brands WHERE name='Citroen'), 'C5'),
((SELECT id FROM brands WHERE name='Citroen'), 'C6'),
((SELECT id FROM brands WHERE name='Citroen'), 'C8'),
((SELECT id FROM brands WHERE name='Citroen'), 'DS3'),
((SELECT id FROM brands WHERE name='Citroen'), 'DS4'),
((SELECT id FROM brands WHERE name='Citroen'), 'DS5'),
((SELECT id FROM brands WHERE name='Citroen'), 'Berlingo'),
((SELECT id FROM brands WHERE name='Citroen'), 'Jumper'),
((SELECT id FROM brands WHERE name='Citroen'), 'Jumpy'),
((SELECT id FROM brands WHERE name='Citroen'), 'Xantia'),
((SELECT id FROM brands WHERE name='Citroen'), 'Xsara'),
((SELECT id FROM brands WHERE name='Citroen'), 'Xsara Picasso'),
((SELECT id FROM brands WHERE name='Citroen'), 'Saxo'),
((SELECT id FROM brands WHERE name='Citroen'), '2CV'),
((SELECT id FROM brands WHERE name='Citroen'), 'C15'),
((SELECT id FROM brands WHERE name='Citroen'), 'C5 Aircross'),
((SELECT id FROM brands WHERE name='Citroen'), 'C4 Picasso'),
((SELECT id FROM brands WHERE name='Citroen'), 'Grand C4 Picasso');

-- Dacia
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Dacia'), '1300'),
((SELECT id FROM brands WHERE name='Dacia'), '1410'),
((SELECT id FROM brands WHERE name='Dacia'), '1310'),
((SELECT id FROM brands WHERE name='Dacia'), 'Logan'),
((SELECT id FROM brands WHERE name='Dacia'), 'Sandero'),
((SELECT id FROM brands WHERE name='Dacia'), 'Duster'),
((SELECT id FROM brands WHERE name='Dacia'), 'Lodgy'),
((SELECT id FROM brands WHERE name='Dacia'), 'Dokker'),
((SELECT id FROM brands WHERE name='Dacia'), 'Jogger'),
((SELECT id FROM brands WHERE name='Dacia'), 'Solenza'),
((SELECT id FROM brands WHERE name='Dacia'), 'SuperNova'),
((SELECT id FROM brands WHERE name='Dacia'), 'Spring');

-- Daewoo
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Daewoo'), 'Tico'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Lanos'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Nubira'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Leganza'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Matiz'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Espero'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Kalos'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Korando'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Musso'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Tacuma'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Evanda'),
((SELECT id FROM brands WHERE name='Daewoo'), 'Nexia');

-- DAF
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='DAF'), 'XF'),
((SELECT id FROM brands WHERE name='DAF'), 'CF'),
((SELECT id FROM brands WHERE name='DAF'), 'LF'),
((SELECT id FROM brands WHERE name='DAF'), 'SB220'),
((SELECT id FROM brands WHERE name='DAF'), '95'),
((SELECT id FROM brands WHERE name='DAF'), 'Super Space Cab');

-- De Tomaso
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='De Tomaso'), 'Pantera'),
((SELECT id FROM brands WHERE name='De Tomaso'), 'Mangusta'),
((SELECT id FROM brands WHERE name='De Tomaso'), 'Guara'),
((SELECT id FROM brands WHERE name='De Tomaso'), 'Vallelunga'),
((SELECT id FROM brands WHERE name='De Tomaso'), 'P72');

-- Dodge
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Dodge'), 'Charger'),
((SELECT id FROM brands WHERE name='Dodge'), 'Challenger'),
((SELECT id FROM brands WHERE name='Dodge'), 'Viper'),
((SELECT id FROM brands WHERE name='Dodge'), 'Durango'),
((SELECT id FROM brands WHERE name='Dodge'), 'Journey'),
((SELECT id FROM brands WHERE name='Dodge'), 'Caliber'),
((SELECT id FROM brands WHERE name='Dodge'), 'Avenger'),
((SELECT id FROM brands WHERE name='Dodge'), 'Nitro'),
((SELECT id FROM brands WHERE name='Dodge'), 'Ram'),
((SELECT id FROM brands WHERE name='Dodge'), 'Dart');

-- Ducati
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Ducati'), 'Panigale V2'),
((SELECT id FROM brands WHERE name='Ducati'), 'Panigale V4'),
((SELECT id FROM brands WHERE name='Ducati'), 'Monster'),
((SELECT id FROM brands WHERE name='Ducati'), '900 SS'),
((SELECT id FROM brands WHERE name='Ducati'), 'Multistrada'),
((SELECT id FROM brands WHERE name='Ducati'), 'Streetfighter'),
((SELECT id FROM brands WHERE name='Ducati'), 'Scrambler'),
((SELECT id FROM brands WHERE name='Ducati'), 'Diavel'),
((SELECT id FROM brands WHERE name='Ducati'), 'SuperSport'),
((SELECT id FROM brands WHERE name='Ducati'), 'Desmosedici'),
((SELECT id FROM brands WHERE name='Ducati'), 'Hypermotard');

-- Ferrari
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Ferrari'), 'F430'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Testarossa'),
((SELECT id FROM brands WHERE name='Ferrari'), 'F40'),
((SELECT id FROM brands WHERE name='Ferrari'), 'F50'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Enzo'),
((SELECT id FROM brands WHERE name='Ferrari'), 'LaFerrari'),
((SELECT id FROM brands WHERE name='Ferrari'), '488 GTB'),
((SELECT id FROM brands WHERE name='Ferrari'), '812 Superfast'),
((SELECT id FROM brands WHERE name='Ferrari'), 'SF90 Stradale'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Roma'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Portofino'),
((SELECT id FROM brands WHERE name='Ferrari'), 'F8 Tributo'),
((SELECT id FROM brands WHERE name='Ferrari'), '458 Italia'),
((SELECT id FROM brands WHERE name='Ferrari'), 'California'),
((SELECT id FROM brands WHERE name='Ferrari'), '360 Modena'),
((SELECT id FROM brands WHERE name='Ferrari'), '308 GTB'),
((SELECT id FROM brands WHERE name='Ferrari'), '328'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Mondial'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Daytona SP3'),
((SELECT id FROM brands WHERE name='Ferrari'), 'Purosangue');

-- Fiat
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Fiat'), '126p'),
((SELECT id FROM brands WHERE name='Fiat'), '125p'),
((SELECT id FROM brands WHERE name='Fiat'), '131 Mirafiori'),
((SELECT id FROM brands WHERE name='Fiat'), 'Punto'),
((SELECT id FROM brands WHERE name='Fiat'), 'Stilo'),
((SELECT id FROM brands WHERE name='Fiat'), '500'),
((SELECT id FROM brands WHERE name='Fiat'), '500L'),
((SELECT id FROM brands WHERE name='Fiat'), '500X'),
((SELECT id FROM brands WHERE name='Fiat'), 'Panda'),
((SELECT id FROM brands WHERE name='Fiat'), 'Cinquecento'),
((SELECT id FROM brands WHERE name='Fiat'), 'Seicento'),
((SELECT id FROM brands WHERE name='Fiat'), 'Bravo'),
((SELECT id FROM brands WHERE name='Fiat'), 'Brava'),
((SELECT id FROM brands WHERE name='Fiat'), 'Marea'),
((SELECT id FROM brands WHERE name='Fiat'), 'Croma'),
((SELECT id FROM brands WHERE name='Fiat'), 'Tempra'),
((SELECT id FROM brands WHERE name='Fiat'), 'Tipo'),
((SELECT id FROM brands WHERE name='Fiat'), 'Uno'),
((SELECT id FROM brands WHERE name='Fiat'), 'Ducato'),
((SELECT id FROM brands WHERE name='Fiat'), 'Scudo'),
((SELECT id FROM brands WHERE name='Fiat'), 'Talento'),
((SELECT id FROM brands WHERE name='Fiat'), 'Palio'),
((SELECT id FROM brands WHERE name='Fiat'), 'Siena'),
((SELECT id FROM brands WHERE name='Fiat'), 'Strada'),
((SELECT id FROM brands WHERE name='Fiat'), 'Fullback'),
((SELECT id FROM brands WHERE name='Fiat'), '124 Spider'),
((SELECT id FROM brands WHERE name='Fiat'), '124 Sport'),
((SELECT id FROM brands WHERE name='Fiat'), 'Barchetta'),
((SELECT id FROM brands WHERE name='Fiat'), 'Coupe'),
((SELECT id FROM brands WHERE name='Fiat'), 'Doblo'),
((SELECT id FROM brands WHERE name='Fiat'), 'Fiorino'),
((SELECT id FROM brands WHERE name='Fiat'), 'Idea'),
((SELECT id FROM brands WHERE name='Fiat'), 'Linea'),
((SELECT id FROM brands WHERE name='Fiat'), 'Multipla'),
((SELECT id FROM brands WHERE name='Fiat'), 'Panda 4x4'),
((SELECT id FROM brands WHERE name='Fiat'), 'X1/9'),
((SELECT id FROM brands WHERE name='Fiat'), 'Ritmo'),
((SELECT id FROM brands WHERE name='Fiat'), 'Regata'),
((SELECT id FROM brands WHERE name='Fiat'), 'Argenta'),
((SELECT id FROM brands WHERE name='Fiat'), '132'),
((SELECT id FROM brands WHERE name='Fiat'), '127'),
((SELECT id FROM brands WHERE name='Fiat'), '128');

-- Ford
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Ford'), 'Escort'),
((SELECT id FROM brands WHERE name='Ford'), 'Sierra'),
((SELECT id FROM brands WHERE name='Ford'), 'Mondeo IV'),
((SELECT id FROM brands WHERE name='Ford'), 'Mondeo'),
((SELECT id FROM brands WHERE name='Ford'), 'Fusion'),
((SELECT id FROM brands WHERE name='Ford'), 'Focus'),
((SELECT id FROM brands WHERE name='Ford'), 'Fiesta'),
((SELECT id FROM brands WHERE name='Ford'), 'Ka'),
((SELECT id FROM brands WHERE name='Ford'), 'Puma'),
((SELECT id FROM brands WHERE name='Ford'), 'Kuga'),
((SELECT id FROM brands WHERE name='Ford'), 'EcoSport'),
((SELECT id FROM brands WHERE name='Ford'), 'Ranger'),
((SELECT id FROM brands WHERE name='Ford'), 'Transit'),
((SELECT id FROM brands WHERE name='Ford'), 'Transit Connect'),
((SELECT id FROM brands WHERE name='Ford'), 'Transit Custom'),
((SELECT id FROM brands WHERE name='Ford'), 'Mustang'),
((SELECT id FROM brands WHERE name='Ford'), 'Edge'),
((SELECT id FROM brands WHERE name='Ford'), 'Galaxy'),
((SELECT id FROM brands WHERE name='Ford'), 'S-Max'),
((SELECT id FROM brands WHERE name='Ford'), 'C-Max'),
((SELECT id FROM brands WHERE name='Ford'), 'Grand C-Max'),
((SELECT id FROM brands WHERE name='Ford'), 'Tourneo Courier'),
((SELECT id FROM brands WHERE name='Ford'), 'Tourneo Custom'),
((SELECT id FROM brands WHERE name='Ford'), 'Probe'),
((SELECT id FROM brands WHERE name='Ford'), 'Scorpio'),
((SELECT id FROM brands WHERE name='Ford'), 'Granada'),
((SELECT id FROM brands WHERE name='Ford'), 'Taunus'),
((SELECT id FROM brands WHERE name='Ford'), 'Capri'),
((SELECT id FROM brands WHERE name='Ford'), 'Orion'),
((SELECT id FROM brands WHERE name='Ford'), 'Bronco'),
((SELECT id FROM brands WHERE name='Ford'), 'Maverick'),
((SELECT id FROM brands WHERE name='Ford'), 'Explorer'),
((SELECT id FROM brands WHERE name='Ford'), 'GT'),
((SELECT id FROM brands WHERE name='Ford'), 'Focus RS'),
((SELECT id FROM brands WHERE name='Ford'), 'F-150'),
((SELECT id FROM brands WHERE name='Ford'), 'Mustang Mach-E');

-- Harley-Davidson
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Iron 883'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Street 750'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Fat Boy'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Road King'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Street Glide'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Electra Glide'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Sportster'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Softail'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'V-Rod'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Dyna'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Nightster'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Heritage Classic'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'CVO'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'LiveWire'),
((SELECT id FROM brands WHERE name='Harley-Davidson'), 'Pan America');

-- Honda
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Honda'), 'Accord VI'),
((SELECT id FROM brands WHERE name='Honda'), 'Accord'),
((SELECT id FROM brands WHERE name='Honda'), 'Civic VIII'),
((SELECT id FROM brands WHERE name='Honda'), 'Civic'),
((SELECT id FROM brands WHERE name='Honda'), 'Jazz'),
((SELECT id FROM brands WHERE name='Honda'), 'Prelude'),
((SELECT id FROM brands WHERE name='Honda'), 'CR-V'),
((SELECT id FROM brands WHERE name='Honda'), 'HR-V'),
((SELECT id FROM brands WHERE name='Honda'), 'Legend'),
((SELECT id FROM brands WHERE name='Honda'), 'Integra'),
((SELECT id FROM brands WHERE name='Honda'), 'NSX'),
((SELECT id FROM brands WHERE name='Honda'), 'S2000'),
((SELECT id FROM brands WHERE name='Honda'), 'CRX'),
((SELECT id FROM brands WHERE name='Honda'), 'FR-V'),
((SELECT id FROM brands WHERE name='Honda'), 'Stream'),
((SELECT id FROM brands WHERE name='Honda'), 'CBR 1000R'),
((SELECT id FROM brands WHERE name='Honda'), 'CBR 600RR'),
((SELECT id FROM brands WHERE name='Honda'), 'VFR 750'),
((SELECT id FROM brands WHERE name='Honda'), 'VFR 800'),
((SELECT id FROM brands WHERE name='Honda'), 'Gold Wing'),
((SELECT id FROM brands WHERE name='Honda'), 'Africa Twin'),
((SELECT id FROM brands WHERE name='Honda'), 'XR 650'),
((SELECT id FROM brands WHERE name='Honda'), 'CB 500'),
((SELECT id FROM brands WHERE name='Honda'), 'CB 750'),
((SELECT id FROM brands WHERE name='Honda'), 'CB 1000R'),
((SELECT id FROM brands WHERE name='Honda'), 'CBF 600'),
((SELECT id FROM brands WHERE name='Honda'), 'Shadow'),
((SELECT id FROM brands WHERE name='Honda'), 'PCX'),

-- Hummer
((SELECT id FROM brands WHERE name='Hummer'), 'H1'),
((SELECT id FROM brands WHERE name='Hummer'), 'H2'),
((SELECT id FROM brands WHERE name='Hummer'), 'H3');

-- Hyundai
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Hyundai'), 'i30'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Elantra'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Accent'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Sonata'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Tucson'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Santa Fe'),
((SELECT id FROM brands WHERE name='Hyundai'), 'ix35'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Kona'),
((SELECT id FROM brands WHERE name='Hyundai'), 'i10'),
((SELECT id FROM brands WHERE name='Hyundai'), 'i20'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Getz'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Matrix'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Trajet'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Coupe'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Genesis'),
((SELECT id FROM brands WHERE name='Hyundai'), 'IONIQ 5'),
((SELECT id FROM brands WHERE name='Hyundai'), 'IONIQ 6'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Nexo'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Staria'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Palisade'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Bayon'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Lantra'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Pony'),
((SELECT id FROM brands WHERE name='Hyundai'), 'Atos');

-- Ikarus
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Ikarus'), '280'),
((SELECT id FROM brands WHERE name='Ikarus'), '260'),
((SELECT id FROM brands WHERE name='Ikarus'), '256'),
((SELECT id FROM brands WHERE name='Ikarus'), '435'),
((SELECT id FROM brands WHERE name='Ikarus'), '412'),
((SELECT id FROM brands WHERE name='Ikarus'), 'E91'),
((SELECT id FROM brands WHERE name='Ikarus'), '211'),
((SELECT id FROM brands WHERE name='Ikarus'), '55'),
((SELECT id FROM brands WHERE name='Ikarus'), '66'),
((SELECT id FROM brands WHERE name='Ikarus'), '180'),
((SELECT id FROM brands WHERE name='Ikarus'), '30'),
((SELECT id FROM brands WHERE name='Ikarus'), '31'),
((SELECT id FROM brands WHERE name='Ikarus'), '620'),
((SELECT id FROM brands WHERE name='Ikarus'), '630');

-- Isuzu
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Isuzu'), 'Trooper'),
((SELECT id FROM brands WHERE name='Isuzu'), 'D-Max'),
((SELECT id FROM brands WHERE name='Isuzu'), 'Rodeo'),
((SELECT id FROM brands WHERE name='Isuzu'), 'Mu-X'),
((SELECT id FROM brands WHERE name='Isuzu'), 'N-Series'),
((SELECT id FROM brands WHERE name='Isuzu'), 'Gemini'),
((SELECT id FROM brands WHERE name='Isuzu'), 'Piazza');

-- Iveco
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Iveco'), 'Stralis'),
((SELECT id FROM brands WHERE name='Iveco'), 'Daily'),
((SELECT id FROM brands WHERE name='Iveco'), 'Eurocargo'),
((SELECT id FROM brands WHERE name='Iveco'), 'Trakker'),
((SELECT id FROM brands WHERE name='Iveco'), 'Urbanway'),
((SELECT id FROM brands WHERE name='Iveco'), 'S-Way'),
((SELECT id FROM brands WHERE name='Iveco'), 'TurboDaily'),
((SELECT id FROM brands WHERE name='Iveco'), 'Massif'),
((SELECT id FROM brands WHERE name='Iveco'), 'Iveco 190'),
((SELECT id FROM brands WHERE name='Iveco'), 'Unic'),
((SELECT id FROM brands WHERE name='Iveco'), 'Magirus'),
((SELECT id FROM brands WHERE name='Iveco'), 'Astra'),
((SELECT id FROM brands WHERE name='Iveco'), 'Crossway');

-- Jaguar
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Jaguar'), 'S-Type'),
((SELECT id FROM brands WHERE name='Jaguar'), 'X-Type'),
((SELECT id FROM brands WHERE name='Jaguar'), 'XJ'),
((SELECT id FROM brands WHERE name='Jaguar'), 'XK'),
((SELECT id FROM brands WHERE name='Jaguar'), 'XF'),
((SELECT id FROM brands WHERE name='Jaguar'), 'XE'),
((SELECT id FROM brands WHERE name='Jaguar'), 'F-Type'),
((SELECT id FROM brands WHERE name='Jaguar'), 'E-Pace'),
((SELECT id FROM brands WHERE name='Jaguar'), 'F-Pace'),
((SELECT id FROM brands WHERE name='Jaguar'), 'I-Pace'),
((SELECT id FROM brands WHERE name='Jaguar'), 'E-Type'),
((SELECT id FROM brands WHERE name='Jaguar'), 'XJ220');

-- Jawa
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Jawa'), '350'),
((SELECT id FROM brands WHERE name='Jawa'), '500'),
((SELECT id FROM brands WHERE name='Jawa'), '250'),
((SELECT id FROM brands WHERE name='Jawa'), '175'),
((SELECT id FROM brands WHERE name='Jawa'), '125'),
((SELECT id FROM brands WHERE name='Jawa'), '640'),
((SELECT id FROM brands WHERE name='Jawa'), '660'),
((SELECT id FROM brands WHERE name='Jawa'), '50 Pionier'),
((SELECT id FROM brands WHERE name='Jawa'), 'Babetta'),
((SELECT id FROM brands WHERE name='Jawa'), 'Perak 250'),
((SELECT id FROM brands WHERE name='Jawa'), '471'),
((SELECT id FROM brands WHERE name='Jawa'), '100');

-- Jelcz
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Jelcz'), '315'),
((SELECT id FROM brands WHERE name='Jelcz'), 'PR110'),
((SELECT id FROM brands WHERE name='Jelcz'), '120M'),
((SELECT id FROM brands WHERE name='Jelcz'), '442'),
((SELECT id FROM brands WHERE name='Jelcz'), '620'),
((SELECT id FROM brands WHERE name='Jelcz'), '300'),
((SELECT id FROM brands WHERE name='Jelcz'), '400'),
((SELECT id FROM brands WHERE name='Jelcz'), 'C-417'),
((SELECT id FROM brands WHERE name='Jelcz'), 'P-01'),
((SELECT id FROM brands WHERE name='Jelcz'), 'M081'),
((SELECT id FROM brands WHERE name='Jelcz'), 'M11'),
((SELECT id FROM brands WHERE name='Jelcz'), 'L100'),
((SELECT id FROM brands WHERE name='Jelcz'), '043'),
((SELECT id FROM brands WHERE name='Jelcz'), '272'),
((SELECT id FROM brands WHERE name='Jelcz'), '300'),
((SELECT id FROM brands WHERE name='Jelcz'), 'S-15'),
((SELECT id FROM brands WHERE name='Jelcz'), 'S-16'),
((SELECT id FROM brands WHERE name='Jelcz'), 'D-10');

-- Jeep
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Jeep'), 'Wrangler'),
((SELECT id FROM brands WHERE name='Jeep'), 'Cherokee'),
((SELECT id FROM brands WHERE name='Jeep'), 'Grand Cherokee'),
((SELECT id FROM brands WHERE name='Jeep'), 'Compass'),
((SELECT id FROM brands WHERE name='Jeep'), 'Renegade'),
((SELECT id FROM brands WHERE name='Jeep'), 'Gladiator'),
((SELECT id FROM brands WHERE name='Jeep'), 'Liberty'),
((SELECT id FROM brands WHERE name='Jeep'), 'Commander'),
((SELECT id FROM brands WHERE name='Jeep'), 'Patriot'),
((SELECT id FROM brands WHERE name='Jeep'), 'CJ-5'),
((SELECT id FROM brands WHERE name='Jeep'), 'CJ-7'),
((SELECT id FROM brands WHERE name='Jeep'), 'Avenger');

-- Karosa
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Karosa'), 'B732'),
((SELECT id FROM brands WHERE name='Karosa'), 'B731'),
((SELECT id FROM brands WHERE name='Karosa'), 'B941'),
((SELECT id FROM brands WHERE name='Karosa'), 'C734'),
((SELECT id FROM brands WHERE name='Karosa'), 'C735'),
((SELECT id FROM brands WHERE name='Karosa'), 'C744'),
((SELECT id FROM brands WHERE name='Karosa'), 'C934'),
((SELECT id FROM brands WHERE name='Karosa'), 'C935'),
((SELECT id FROM brands WHERE name='Karosa'), 'C954'),
((SELECT id FROM brands WHERE name='Karosa'), 'C955'),
((SELECT id FROM brands WHERE name='Karosa'), 'HD 12'),
((SELECT id FROM brands WHERE name='Karosa'), 'LC 735'),
((SELECT id FROM brands WHERE name='Karosa'), 'LC 757'),
((SELECT id FROM brands WHERE name='Karosa'), 'B652'),
((SELECT id FROM brands WHERE name='Karosa'), 'SL 11'),
((SELECT id FROM brands WHERE name='Karosa'), 'SM 11');

-- Kawasaki
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Kawasaki'), 'Z900'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'ZX-9R'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Ninja ZX-10R'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Ninja ZX-6R'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Ninja 650'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Vulcan'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Versys'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'ER-5'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'ER-6n'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'KX 250'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'KX 450'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Z650'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'Z900RS'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'ZZR 1400'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'GPZ 500'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'GPZ 900R'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'H2'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'ZRX 1100'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'W800'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'KLE 500'),
((SELECT id FROM brands WHERE name='Kawasaki'), 'KLR 650');

-- Kia
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Kia'), 'Ceed'),
((SELECT id FROM brands WHERE name='Kia'), 'Rio'),
((SELECT id FROM brands WHERE name='Kia'), 'Picanto'),
((SELECT id FROM brands WHERE name='Kia'), 'Sportage'),
((SELECT id FROM brands WHERE name='Kia'), 'Sorento'),
((SELECT id FROM brands WHERE name='Kia'), 'Optima'),
((SELECT id FROM brands WHERE name='Kia'), 'Stinger'),
((SELECT id FROM brands WHERE name='Kia'), 'Niro'),
((SELECT id FROM brands WHERE name='Kia'), 'EV6'),
((SELECT id FROM brands WHERE name='Kia'), 'EV9'),
((SELECT id FROM brands WHERE name='Kia'), 'Venga'),
((SELECT id FROM brands WHERE name='Kia'), 'Carnival'),
((SELECT id FROM brands WHERE name='Kia'), 'Soul'),
((SELECT id FROM brands WHERE name='Kia'), 'Cerato'),
((SELECT id FROM brands WHERE name='Kia'), 'Magentis'),
((SELECT id FROM brands WHERE name='Kia'), 'Clarus'),
((SELECT id FROM brands WHERE name='Kia'), 'Proceed'),
((SELECT id FROM brands WHERE name='Kia'), 'XCeed'),
((SELECT id FROM brands WHERE name='Kia'), 'Sephia'),
((SELECT id FROM brands WHERE name='Kia'), 'Shuma'),
((SELECT id FROM brands WHERE name='Kia'), 'Carens'),
((SELECT id FROM brands WHERE name='Kia'), 'Pregio'),
((SELECT id FROM brands WHERE name='Kia'), 'Besta'),
((SELECT id FROM brands WHERE name='Kia'), 'Telluride'),
((SELECT id FROM brands WHERE name='Kia'), 'K5'),
((SELECT id FROM brands WHERE name='Kia'), 'K8');

-- KTM
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='KTM'), '890 Adventure'),
((SELECT id FROM brands WHERE name='KTM'), '1290 Super Duke'),
((SELECT id FROM brands WHERE name='KTM'), '390 Duke'),
((SELECT id FROM brands WHERE name='KTM'), '790 Duke'),
((SELECT id FROM brands WHERE name='KTM'), '990 Supermoto'),
((SELECT id FROM brands WHERE name='KTM'), '1190 Adventure'),
((SELECT id FROM brands WHERE name='KTM'), 'SX 125'),
((SELECT id FROM brands WHERE name='KTM'), 'SX 250'),
((SELECT id FROM brands WHERE name='KTM'), 'SX 450'),
((SELECT id FROM brands WHERE name='KTM'), 'EXC 300'),
((SELECT id FROM brands WHERE name='KTM'), 'Freeride E'),
((SELECT id FROM brands WHERE name='KTM'), 'X-Bow');

-- Lada
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lada'), '2105'),
((SELECT id FROM brands WHERE name='Lada'), 'Niva'),
((SELECT id FROM brands WHERE name='Lada'), '2101'),
((SELECT id FROM brands WHERE name='Lada'), '2102'),
((SELECT id FROM brands WHERE name='Lada'), '2103'),
((SELECT id FROM brands WHERE name='Lada'), '2106'),
((SELECT id FROM brands WHERE name='Lada'), '2107'),
((SELECT id FROM brands WHERE name='Lada'), '2108'),
((SELECT id FROM brands WHERE name='Lada'), '2109'),
((SELECT id FROM brands WHERE name='Lada'), '21099'),
((SELECT id FROM brands WHERE name='Lada'), '2110'),
((SELECT id FROM brands WHERE name='Lada'), '2111'),
((SELECT id FROM brands WHERE name='Lada'), '2112'),
((SELECT id FROM brands WHERE name='Lada'), '2121'),
((SELECT id FROM brands WHERE name='Lada'), '2131'),
((SELECT id FROM brands WHERE name='Lada'), 'Samara'),
((SELECT id FROM brands WHERE name='Lada'), 'Vesta'),
((SELECT id FROM brands WHERE name='Lada'), 'Granta'),
((SELECT id FROM brands WHERE name='Lada'), 'Largus'),
((SELECT id FROM brands WHERE name='Lada'), 'X-Ray'),
((SELECT id FROM brands WHERE name='Lada'), 'Priora'),
((SELECT id FROM brands WHERE name='Lada'), 'Kalina');

-- Lamborghini
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lamborghini'), 'Gallardo'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Countach'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Miura'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Diablo'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Murcielago'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Aventador'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Huracan'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Urus'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Revuelto'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'LM 002'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Silhouette'),
((SELECT id FROM brands WHERE name='Lamborghini'), 'Jalpa');

-- Lancia
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lancia'), 'Delta HF'),
((SELECT id FROM brands WHERE name='Lancia'), 'Y'),
((SELECT id FROM brands WHERE name='Lancia'), 'Ypsilon'),
((SELECT id FROM brands WHERE name='Lancia'), 'Thema'),
((SELECT id FROM brands WHERE name='Lancia'), 'Thesis'),
((SELECT id FROM brands WHERE name='Lancia'), 'Lybra'),
((SELECT id FROM brands WHERE name='Lancia'), 'Dedra'),
((SELECT id FROM brands WHERE name='Lancia'), 'Kappa'),
((SELECT id FROM brands WHERE name='Lancia'), 'Zeta'),
((SELECT id FROM brands WHERE name='Lancia'), 'Phedra'),
((SELECT id FROM brands WHERE name='Lancia'), 'Musa'),
((SELECT id FROM brands WHERE name='Lancia'), 'Stratos'),
((SELECT id FROM brands WHERE name='Lancia'), '037'),
((SELECT id FROM brands WHERE name='Lancia'), 'Flavia'),
((SELECT id FROM brands WHERE name='Lancia'), 'Fulvia'),
((SELECT id FROM brands WHERE name='Lancia'), 'Beta'),
((SELECT id FROM brands WHERE name='Lancia'), 'Gamma'),
((SELECT id FROM brands WHERE name='Lancia'), 'Trevi'),
((SELECT id FROM brands WHERE name='Lancia'), 'Prisma');

-- Land Rover
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Land Rover'), 'Defender'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Discovery'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Discovery Sport'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Range Rover'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Range Rover Sport'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Range Rover Evoque'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Range Rover Velar'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Freelander'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Series II'),
((SELECT id FROM brands WHERE name='Land Rover'), 'Series III');

-- Lexus
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lexus'), 'IS200'),
((SELECT id FROM brands WHERE name='Lexus'), 'IS'),
((SELECT id FROM brands WHERE name='Lexus'), 'ES'),
((SELECT id FROM brands WHERE name='Lexus'), 'GS'),
((SELECT id FROM brands WHERE name='Lexus'), 'LS'),
((SELECT id FROM brands WHERE name='Lexus'), 'RX'),
((SELECT id FROM brands WHERE name='Lexus'), 'NX'),
((SELECT id FROM brands WHERE name='Lexus'), 'UX'),
((SELECT id FROM brands WHERE name='Lexus'), 'LX'),
((SELECT id FROM brands WHERE name='Lexus'), 'GX'),
((SELECT id FROM brands WHERE name='Lexus'), 'LC'),
((SELECT id FROM brands WHERE name='Lexus'), 'LFA'),
((SELECT id FROM brands WHERE name='Lexus'), 'SC'),
((SELECT id FROM brands WHERE name='Lexus'), 'CT'),
((SELECT id FROM brands WHERE name='Lexus'), 'RC'),
((SELECT id FROM brands WHERE name='Lexus'), 'RZ');

-- Lincoln
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lincoln'), 'Town Car'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Continental'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Navigator'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Aviator'),
((SELECT id FROM brands WHERE name='Lincoln'), 'MKZ'),
((SELECT id FROM brands WHERE name='Lincoln'), 'MKC'),
((SELECT id FROM brands WHERE name='Lincoln'), 'MKX'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Nautilus'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Corsair'),
((SELECT id FROM brands WHERE name='Lincoln'), 'Zephyr');

-- Lublin
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Lublin'), 'II'),
((SELECT id FROM brands WHERE name='Lublin'), 'III'),
((SELECT id FROM brands WHERE name='Lublin'), '51'),
((SELECT id FROM brands WHERE name='Lublin'), 'TG'),
((SELECT id FROM brands WHERE name='Lublin'), 'LD');

-- MAN
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='MAN'), 'TGX'),
((SELECT id FROM brands WHERE name='MAN'), 'F90'),
((SELECT id FROM brands WHERE name='MAN'), 'NL202'),
((SELECT id FROM brands WHERE name='MAN'), 'TGA'),
((SELECT id FROM brands WHERE name='MAN'), 'TGS'),
((SELECT id FROM brands WHERE name='MAN'), 'TGX'),
((SELECT id FROM brands WHERE name='MAN'), 'Lions City E'),
((SELECT id FROM brands WHERE name='MAN'), 'Lions Coach'),
((SELECT id FROM brands WHERE name='MAN'), 'Lions Intercity'),
((SELECT id FROM brands WHERE name='MAN'), 'Lions City'),
((SELECT id FROM brands WHERE name='MAN'), 'L2000'),
((SELECT id FROM brands WHERE name='MAN'), 'M2000'),
((SELECT id FROM brands WHERE name='MAN'), 'F2000'),
((SELECT id FROM brands WHERE name='MAN'), '19.314'),
((SELECT id FROM brands WHERE name='MAN'), '12.220'),
((SELECT id FROM brands WHERE name='MAN'), 'TG-Le'),
((SELECT id FROM brands WHERE name='MAN'), 'SL 200'),
((SELECT id FROM brands WHERE name='MAN'), 'SD 200'),
((SELECT id FROM brands WHERE name='MAN'), 'SM 152'),
((SELECT id FROM brands WHERE name='MAN'), 'ND 313');

-- Maserati
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Maserati'), 'Biturbo'),
((SELECT id FROM brands WHERE name='Maserati'), 'Ghibli'),
((SELECT id FROM brands WHERE name='Maserati'), 'Quattroporte'),
((SELECT id FROM brands WHERE name='Maserati'), 'GranTurismo'),
((SELECT id FROM brands WHERE name='Maserati'), 'GranCabrio'),
((SELECT id FROM brands WHERE name='Maserati'), 'MC20'),
((SELECT id FROM brands WHERE name='Maserati'), 'Levante'),
((SELECT id FROM brands WHERE name='Maserati'), 'Grecale'),
((SELECT id FROM brands WHERE name='Maserati'), 'Spyder'),
((SELECT id FROM brands WHERE name='Maserati'), '3200 GT'),
((SELECT id FROM brands WHERE name='Maserati'), 'Coupe'),
((SELECT id FROM brands WHERE name='Maserati'), 'Merak'),
((SELECT id FROM brands WHERE name='Maserati'), 'Khamsin'),
((SELECT id FROM brands WHERE name='Maserati'), 'Indy'),
((SELECT id FROM brands WHERE name='Maserati'), 'Mistral');

-- Mazda
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Mazda'), '6'),
((SELECT id FROM brands WHERE name='Mazda'), 'RX-7 FD'),
((SELECT id FROM brands WHERE name='Mazda'), '323'),
((SELECT id FROM brands WHERE name='Mazda'), 'MX-5'),
((SELECT id FROM brands WHERE name='Mazda'), 'CX-5'),
((SELECT id FROM brands WHERE name='Mazda'), 'CX-3'),
((SELECT id FROM brands WHERE name='Mazda'), 'CX-7'),
((SELECT id FROM brands WHERE name='Mazda'), 'CX-9'),
((SELECT id FROM brands WHERE name='Mazda'), 'RX-8'),
((SELECT id FROM brands WHERE name='Mazda'), 'MX-3'),
((SELECT id FROM brands WHERE name='Mazda'), 'MX-6'),
((SELECT id FROM brands WHERE name='Mazda'), '121'),
((SELECT id FROM brands WHERE name='Mazda'), '626'),
((SELECT id FROM brands WHERE name='Mazda'), 'Xedos 6'),
((SELECT id FROM brands WHERE name='Mazda'), 'Xedos 9'),
((SELECT id FROM brands WHERE name='Mazda'), 'Premacy'),
((SELECT id FROM brands WHERE name='Mazda'), 'MPV'),
((SELECT id FROM brands WHERE name='Mazda'), 'B-Series'),
((SELECT id FROM brands WHERE name='Mazda'), 'BT-50'),
((SELECT id FROM brands WHERE name='Mazda'), 'MX-30'),
((SELECT id FROM brands WHERE name='Mazda'), 'Demio'),
((SELECT id FROM brands WHERE name='Mazda'), '2'),
((SELECT id FROM brands WHERE name='Mazda'), '3'),
((SELECT id FROM brands WHERE name='Mazda'), '5'),
((SELECT id FROM brands WHERE name='Mazda'), 'Capella');

-- McLaren
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='McLaren'), '720S'),
((SELECT id FROM brands WHERE name='McLaren'), 'Artura'),
((SELECT id FROM brands WHERE name='McLaren'), '765LT'),
((SELECT id FROM brands WHERE name='McLaren'), 'Senna'),
((SELECT id FROM brands WHERE name='McLaren'), 'P1'),
((SELECT id FROM brands WHERE name='McLaren'), '600LT'),
((SELECT id FROM brands WHERE name='McLaren'), 'GT'),
((SELECT id FROM brands WHERE name='McLaren'), 'F1'),
((SELECT id FROM brands WHERE name='McLaren'), 'MP4-12C'),
((SELECT id FROM brands WHERE name='McLaren'), '570S');

-- Mercedes
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Mercedes'), 'W124'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W201'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W116'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W203'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W205'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W212'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W214'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W123'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W126'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W140'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W210'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W211'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W220'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W221'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W222'),
((SELECT id FROM brands WHERE name='Mercedes'), 'W223'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Citaro G'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Citaro'),
((SELECT id FROM brands WHERE name='Mercedes'), 'O405'),
((SELECT id FROM brands WHERE name='Mercedes'), 'O404'),
((SELECT id FROM brands WHERE name='Mercedes'), 'O303'),
((SELECT id FROM brands WHERE name='Mercedes'), 'O350'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Sprinter'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Vito'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Viano'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Atego'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Actros'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Axor'),
((SELECT id FROM brands WHERE name='Mercedes'), 'SK'),
((SELECT id FROM brands WHERE name='Mercedes'), 'MB 100'),
((SELECT id FROM brands WHERE name='Mercedes'), 'GLA'),
((SELECT id FROM brands WHERE name='Mercedes'), 'GLB'),
((SELECT id FROM brands WHERE name='Mercedes'), 'GLC'),
((SELECT id FROM brands WHERE name='Mercedes'), 'GLE'),
((SELECT id FROM brands WHERE name='Mercedes'), 'GLS'),
((SELECT id FROM brands WHERE name='Mercedes'), 'S-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'E-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'C-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'A-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'B-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'CLK'),
((SELECT id FROM brands WHERE name='Mercedes'), 'CLS'),
((SELECT id FROM brands WHERE name='Mercedes'), 'SL'),
((SELECT id FROM brands WHERE name='Mercedes'), 'SLK'),
((SELECT id FROM brands WHERE name='Mercedes'), 'SLS AMG'),
((SELECT id FROM brands WHERE name='Mercedes'), 'AMG GT'),
((SELECT id FROM brands WHERE name='Mercedes'), 'EQC'),
((SELECT id FROM brands WHERE name='Mercedes'), 'EQS'),
((SELECT id FROM brands WHERE name='Mercedes'), 'EQE'),
((SELECT id FROM brands WHERE name='Mercedes'), 'EQV'),
((SELECT id FROM brands WHERE name='Mercedes'), '190'),
((SELECT id FROM brands WHERE name='Mercedes'), 'V-Class'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Marco Polo'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Unimog'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Zetros'),
((SELECT id FROM brands WHERE name='Mercedes'), 'Econic');

-- MG
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='MG'), 'B GT'),
((SELECT id FROM brands WHERE name='MG'), 'F'),
((SELECT id FROM brands WHERE name='MG'), 'TF'),
((SELECT id FROM brands WHERE name='MG'), 'ZR'),
((SELECT id FROM brands WHERE name='MG'), 'ZS'),
((SELECT id FROM brands WHERE name='MG'), 'ZT'),
((SELECT id FROM brands WHERE name='MG'), '3'),
((SELECT id FROM brands WHERE name='MG'), '5'),
((SELECT id FROM brands WHERE name='MG'), 'HS'),
((SELECT id FROM brands WHERE name='MG'), 'ZS EV'),
((SELECT id FROM brands WHERE name='MG'), 'MG6'),
((SELECT id FROM brands WHERE name='MG'), 'Cyberster'),
((SELECT id FROM brands WHERE name='MG'), 'Marvel R'),
((SELECT id FROM brands WHERE name='MG'), 'Midget'),
((SELECT id FROM brands WHERE name='MG'), 'A'),
((SELECT id FROM brands WHERE name='MG'), 'C'),
((SELECT id FROM brands WHERE name='MG'), 'MGA'),
((SELECT id FROM brands WHERE name='MG'), 'MGB'),
((SELECT id FROM brands WHERE name='MG'), 'MGC');

-- Mini
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Mini'), 'Cooper R50'),
((SELECT id FROM brands WHERE name='Mini'), 'Cooper'),
((SELECT id FROM brands WHERE name='Mini'), 'Cooper S'),
((SELECT id FROM brands WHERE name='Mini'), 'One'),
((SELECT id FROM brands WHERE name='Mini'), 'John Cooper Works'),
((SELECT id FROM brands WHERE name='Mini'), 'Clubman'),
((SELECT id FROM brands WHERE name='Mini'), 'Countryman'),
((SELECT id FROM brands WHERE name='Mini'), 'Paceman'),
((SELECT id FROM brands WHERE name='Mini'), 'Coupe'),
((SELECT id FROM brands WHERE name='Mini'), 'Roadster'),
((SELECT id FROM brands WHERE name='Mini'), 'Crossover'),
((SELECT id FROM brands WHERE name='Mini'), 'Aceman'),
((SELECT id FROM brands WHERE name='Mini'), 'Electric'),
((SELECT id FROM brands WHERE name='Mini'), 'Original'),
((SELECT id FROM brands WHERE name='Mini'), 'Classic Mini');

-- Mitsubishi
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Lancer Evo X'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Galant'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Carisma'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Space Star'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Colt'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Outlander'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'ASX'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Pajero'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'L200'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Space Wagon'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Eclipse'),
((SELECT id FROM brands WHERE name='Mitsubishi'), '3000 GT'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Starion'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'i-MiEV'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Grandis'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Lancer'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Lancer Evo IX'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Pajero Pinin'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Montero'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Delica'),
((SELECT id FROM brands WHERE name='Mitsubishi'), 'Eclipse Cross');

-- Moto Guzzi
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'California'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'V7'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'V9'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'V85'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Mandalello'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Griso'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Stelvio'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Bellagio'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Norge'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Breva'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Le Mans'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Daytona'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'T3'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Guzzi'),
((SELECT id FROM brands WHERE name='Moto Guzzi'), 'Falcone');

-- Neoplan
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Neoplan'), 'Tourliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Cityliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Skyliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Jumbocruiser'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Starliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Transliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Euroliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'N 4016'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Centroliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Tourliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Jetliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Hamburger'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Megaliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Spaceliner'),
((SELECT id FROM brands WHERE name='Neoplan'), 'Trendliner');

-- Nissan
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Nissan'), 'Skyline R34'),
((SELECT id FROM brands WHERE name='Nissan'), 'Primera'),
((SELECT id FROM brands WHERE name='Nissan'), 'Qashqai'),
((SELECT id FROM brands WHERE name='Nissan'), 'Almera'),
((SELECT id FROM brands WHERE name='Nissan'), 'Micra'),
((SELECT id FROM brands WHERE name='Nissan'), 'Note'),
((SELECT id FROM brands WHERE name='Nissan'), 'Juke'),
((SELECT id FROM brands WHERE name='Nissan'), 'X-Trail'),
((SELECT id FROM brands WHERE name='Nissan'), 'Pathfinder'),
((SELECT id FROM brands WHERE name='Nissan'), 'Navara'),
((SELECT id FROM brands WHERE name='Nissan'), 'GT-R'),
((SELECT id FROM brands WHERE name='Nissan'), '350Z'),
((SELECT id FROM brands WHERE name='Nissan'), '370Z'),
((SELECT id FROM brands WHERE name='Nissan'), 'Leaf'),
((SELECT id FROM brands WHERE name='Nissan'), 'Maxima'),
((SELECT id FROM brands WHERE name='Nissan'), 'Patrol'),
((SELECT id FROM brands WHERE name='Nissan'), 'Terrano'),
((SELECT id FROM brands WHERE name='Nissan'), 'Sunny'),
((SELECT id FROM brands WHERE name='Nissan'), 'Sentra'),
((SELECT id FROM brands WHERE name='Nissan'), 'Serena'),
((SELECT id FROM brands WHERE name='Nissan'), 'Murano'),
((SELECT id FROM brands WHERE name='Nissan'), '200SX'),
((SELECT id FROM brands WHERE name='Nissan'), '300ZX'),
((SELECT id FROM brands WHERE name='Nissan'), 'Figaro'),
((SELECT id FROM brands WHERE name='Nissan'), 'Cube'),
((SELECT id FROM brands WHERE name='Nissan'), 'Pixo'),
((SELECT id FROM brands WHERE name='Nissan'), 'Nv200'),
((SELECT id FROM brands WHERE name='Nissan'), 'e-NV200'),
((SELECT id FROM brands WHERE name='Nissan'), 'Ariya');

-- Opel
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Opel'), 'Kadett'),
((SELECT id FROM brands WHERE name='Opel'), 'Vectra B'),
((SELECT id FROM brands WHERE name='Opel'), 'Insignia'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra F'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra G'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra H'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra J'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra K'),
((SELECT id FROM brands WHERE name='Opel'), 'Astra L'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa A'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa B'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa C'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa D'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa E'),
((SELECT id FROM brands WHERE name='Opel'), 'Corsa F'),
((SELECT id FROM brands WHERE name='Opel'), 'Rekord E'),
((SELECT id FROM brands WHERE name='Opel'), 'Omega A'),
((SELECT id FROM brands WHERE name='Opel'), 'Omega B'),
((SELECT id FROM brands WHERE name='Opel'), 'Calibra'),
((SELECT id FROM brands WHERE name='Opel'), 'Tigra'),
((SELECT id FROM brands WHERE name='Opel'), 'Agila'),
((SELECT id FROM brands WHERE name='Opel'), 'Meriva'),
((SELECT id FROM brands WHERE name='Opel'), 'Zafira A'),
((SELECT id FROM brands WHERE name='Opel'), 'Zafira B'),
((SELECT id FROM brands WHERE name='Opel'), 'Zafira C'),
((SELECT id FROM brands WHERE name='Opel'), 'Signum'),
((SELECT id FROM brands WHERE name='Opel'), 'Speedster'),
((SELECT id FROM brands WHERE name='Opel'), 'GT'),
((SELECT id FROM brands WHERE name='Opel'), 'Manta'),
((SELECT id FROM brands WHERE name='Opel'), 'Ascona'),
((SELECT id FROM brands WHERE name='Opel'), 'Monza'),
((SELECT id FROM brands WHERE name='Opel'), 'Senator'),
((SELECT id FROM brands WHERE name='Opel'), 'Diplomat'),
((SELECT id FROM brands WHERE name='Opel'), 'Admiral'),
((SELECT id FROM brands WHERE name='Opel'), 'Kapitan'),
((SELECT id FROM brands WHERE name='Opel'), 'Commodore'),
((SELECT id FROM brands WHERE name='Opel'), 'Campo'),
((SELECT id FROM brands WHERE name='Opel'), 'Movano'),
((SELECT id FROM brands WHERE name='Opel'), 'Vivaro'),
((SELECT id FROM brands WHERE name='Opel'), 'Combo'),
((SELECT id FROM brands WHERE name='Opel'), 'Ampersand-e'),
((SELECT id FROM brands WHERE name='Opel'), 'Cascada'),
((SELECT id FROM brands WHERE name='Opel'), 'Adam'),
((SELECT id FROM brands WHERE name='Opel'), 'Karl'),
((SELECT id FROM brands WHERE name='Opel'), 'Crossland'),
((SELECT id FROM brands WHERE name='Opel'), 'Grandland'),
((SELECT id FROM brands WHERE name='Opel'), 'Mokka'),
((SELECT id FROM brands WHERE name='Opel'), 'Frontera'),
((SELECT id FROM brands WHERE name='Opel'), 'Monterey'),
((SELECT id FROM brands WHERE name='Opel'), 'Sintra');

-- Peugeot
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Peugeot'), '406'),
((SELECT id FROM brands WHERE name='Peugeot'), '205'),
((SELECT id FROM brands WHERE name='Peugeot'), '307'),
((SELECT id FROM brands WHERE name='Peugeot'), '308 II'),
((SELECT id FROM brands WHERE name='Peugeot'), '306'),
((SELECT id FROM brands WHERE name='Peugeot'), '206'),
((SELECT id FROM brands WHERE name='Peugeot'), '207'),
((SELECT id FROM brands WHERE name='Peugeot'), '208'),
((SELECT id FROM brands WHERE name='Peugeot'), '308'),
((SELECT id FROM brands WHERE name='Peugeot'), '405'),
((SELECT id FROM brands WHERE name='Peugeot'), '407'),
((SELECT id FROM brands WHERE name='Peugeot'), '508'),
((SELECT id FROM brands WHERE name='Peugeot'), '605'),
((SELECT id FROM brands WHERE name='Peugeot'), '607'),
((SELECT id FROM brands WHERE name='Peugeot'), '104'),
((SELECT id FROM brands WHERE name='Peugeot'), '106'),
((SELECT id FROM brands WHERE name='Peugeot'), '107'),
((SELECT id FROM brands WHERE name='Peugeot'), '108'),
((SELECT id FROM brands WHERE name='Peugeot'), '1007'),
((SELECT id FROM brands WHERE name='Peugeot'), '2008'),
((SELECT id FROM brands WHERE name='Peugeot'), '3008'),
((SELECT id FROM brands WHERE name='Peugeot'), '4007'),
((SELECT id FROM brands WHERE name='Peugeot'), '4008'),
((SELECT id FROM brands WHERE name='Peugeot'), '5008'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Ranch'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Boxer'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Partner'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Expert'),
((SELECT id FROM brands WHERE name='Peugeot'), 'J5'),
((SELECT id FROM brands WHERE name='Peugeot'), 'RCZ'),
((SELECT id FROM brands WHERE name='Peugeot'), '504'),
((SELECT id FROM brands WHERE name='Peugeot'), '505'),
((SELECT id FROM brands WHERE name='Peugeot'), '604'),
((SELECT id FROM brands WHERE name='Peugeot'), '305'),
((SELECT id FROM brands WHERE name='Peugeot'), '309'),
((SELECT id FROM brands WHERE name='Peugeot'), '203'),
((SELECT id FROM brands WHERE name='Peugeot'), '403'),
((SELECT id FROM brands WHERE name='Peugeot'), '404'),
((SELECT id FROM brands WHERE name='Peugeot'), 'e-2008'),
((SELECT id FROM brands WHERE name='Peugeot'), 'e-208'),
((SELECT id FROM brands WHERE name='Peugeot'), 'e-308'),
((SELECT id FROM brands WHERE name='Peugeot'), 'e-Rifter'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Rifter'),
((SELECT id FROM brands WHERE name='Peugeot'), 'Traveller');

-- Polski Fiat
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Polski Fiat'), '126p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '125p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '132p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '127p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '128p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '130p'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '1500'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '508'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '518'),
((SELECT id FROM brands WHERE name='Polski Fiat'), '524');

-- Porsche
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Porsche'), '911 996'),
((SELECT id FROM brands WHERE name='Porsche'), '944'),
((SELECT id FROM brands WHERE name='Porsche'), '911'),
((SELECT id FROM brands WHERE name='Porsche'), 'Boxster'),
((SELECT id FROM brands WHERE name='Porsche'), 'Cayman'),
((SELECT id FROM brands WHERE name='Porsche'), 'Panamera'),
((SELECT id FROM brands WHERE name='Porsche'), 'Cayenne'),
((SELECT id FROM brands WHERE name='Porsche'), 'Macan'),
((SELECT id FROM brands WHERE name='Porsche'), 'Taycan'),
((SELECT id FROM brands WHERE name='Porsche'), '918 Spyder'),
((SELECT id FROM brands WHERE name='Porsche'), 'Carrera GT'),
((SELECT id FROM brands WHERE name='Porsche'), '928'),
((SELECT id FROM brands WHERE name='Porsche'), '924'),
((SELECT id FROM brands WHERE name='Porsche'), '959'),
((SELECT id FROM brands WHERE name='Porsche'), '356'),
((SELECT id FROM brands WHERE name='Porsche'), '550 Spyder'),
((SELECT id FROM brands WHERE name='Porsche'), 'Mission E');

-- Renault
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Renault'), 'Megane II'),
((SELECT id FROM brands WHERE name='Renault'), 'Clio I'),
((SELECT id FROM brands WHERE name='Renault'), 'Laguna II'),
((SELECT id FROM brands WHERE name='Renault'), 'Twingo II'),
((SELECT id FROM brands WHERE name='Renault'), 'Megane IV'),
((SELECT id FROM brands WHERE name='Renault'), 'Twingo'),
((SELECT id FROM brands WHERE name='Renault'), 'Clio'),
((SELECT id FROM brands WHERE name='Renault'), 'Megane'),
((SELECT id FROM brands WHERE name='Renault'), 'Laguna'),
((SELECT id FROM brands WHERE name='Renault'), 'Master'),
((SELECT id FROM brands WHERE name='Renault'), 'Magnum'),
((SELECT id FROM brands WHERE name='Renault'), 'Kangoo'),
((SELECT id FROM brands WHERE name='Renault'), 'Trafic'),
((SELECT id FROM brands WHERE name='Renault'), 'Espace'),
((SELECT id FROM brands WHERE name='Renault'), 'Vel Satis'),
((SELECT id FROM brands WHERE name='Renault'), 'Avantime'),
((SELECT id FROM brands WHERE name='Renault'), 'Scenic'),
((SELECT id FROM brands WHERE name='Renault'), 'Grand Scenic'),
((SELECT id FROM brands WHERE name='Renault'), 'Megan'),
((SELECT id FROM brands WHERE name='Renault'), 'Captur'),
((SELECT id FROM brands WHERE name='Renault'), 'Kadjar'),
((SELECT id FROM brands WHERE name='Renault'), 'Arkana'),
((SELECT id FROM brands WHERE name='Renault'), 'Austral'),
((SELECT id FROM brands WHERE name='Renault'), 'Symbioz'),
((SELECT id FROM brands WHERE name='Renault'), 'Rafale'),
((SELECT id FROM brands WHERE name='Renault'), 'Zoe'),
((SELECT id FROM brands WHERE name='Renault'), 'Twizy'),
((SELECT id FROM brands WHERE name='Renault'), 'Fluence'),
((SELECT id FROM brands WHERE name='Renault'), 'Koleos'),
((SELECT id FROM brands WHERE name='Renault'), 'Talisman'),
((SELECT id FROM brands WHERE name='Renault'), 'Latitude'),
((SELECT id FROM brands WHERE name='Renault'), 'Wind'),
((SELECT id FROM brands WHERE name='Renault'), 'R5'),
((SELECT id FROM brands WHERE name='Renault'), 'R4'),
((SELECT id FROM brands WHERE name='Renault'), 'R19'),
((SELECT id FROM brands WHERE name='Renault'), 'R21'),
((SELECT id FROM brands WHERE name='Renault'), 'R25'),
((SELECT id FROM brands WHERE name='Renault'), 'Fuego'),
((SELECT id FROM brands WHERE name='Renault'), 'Alpine A110'),
((SELECT id FROM brands WHERE name='Renault'), '5 E-Tech'),
((SELECT id FROM brands WHERE name='Renault'), 'Scenic E-Tech'),
((SELECT id FROM brands WHERE name='Renault'), '4 E-Tech');

-- Rolls-Royce
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Phantom'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Ghost'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Wraith'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Dawn'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Cullinan'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Spectre'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Silver Shadow'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Silver Cloud'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Silver Spirit'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Corniche'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Park Ward'),
((SELECT id FROM brands WHERE name='Rolls-Royce'), 'Camargue');

-- Rover
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Rover'), '75'),
((SELECT id FROM brands WHERE name='Rover'), '25'),
((SELECT id FROM brands WHERE name='Rover'), '45'),
((SELECT id FROM brands WHERE name='Rover'), '200'),
((SELECT id FROM brands WHERE name='Rover'), '400'),
((SELECT id FROM brands WHERE name='Rover'), '600'),
((SELECT id FROM brands WHERE name='Rover'), '800'),
((SELECT id FROM brands WHERE name='Rover'), 'Streetwise'),
((SELECT id FROM brands WHERE name='Rover'), 'Metro'),
((SELECT id FROM brands WHERE name='Rover'), '100'),
((SELECT id FROM brands WHERE name='Rover'), 'Mini'),
((SELECT id FROM brands WHERE name='Rover'), 'SD1'),
((SELECT id FROM brands WHERE name='Rover'), 'P5'),
((SELECT id FROM brands WHERE name='Rover'), 'P6'),
((SELECT id FROM brands WHERE name='Rover'), '3500'),
((SELECT id FROM brands WHERE name='Rover'), 'Maestro'),
((SELECT id FROM brands WHERE name='Rover'), 'Montego');

-- Saab
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Saab'), '900'),
((SELECT id FROM brands WHERE name='Saab'), '9000'),
((SELECT id FROM brands WHERE name='Saab'), '9-3'),
((SELECT id FROM brands WHERE name='Saab'), '9-5'),
((SELECT id FROM brands WHERE name='Saab'), '9-2X'),
((SELECT id FROM brands WHERE name='Saab'), '9-4X'),
((SELECT id FROM brands WHERE name='Saab'), '96'),
((SELECT id FROM brands WHERE name='Saab'), '95'),
((SELECT id FROM brands WHERE name='Saab'), '99'),
((SELECT id FROM brands WHERE name='Saab'), 'Sonett'),
((SELECT id FROM brands WHERE name='Saab'), 'Phoenix'),
((SELECT id FROM brands WHERE name='Saab'), 'EV-1');

-- Scania
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Scania'), 'R460'),
((SELECT id FROM brands WHERE name='Scania'), '113'),
((SELECT id FROM brands WHERE name='Scania'), 'OmniCity'),
((SELECT id FROM brands WHERE name='Scania'), 'Citywide'),
((SELECT id FROM brands WHERE name='Scania'), 'O4'),
((SELECT id FROM brands WHERE name='Scania'), 'CN94'),
((SELECT id FROM brands WHERE name='Scania'), 'R-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'G-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'P-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'S-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'T-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'Irizar i6'),
((SELECT id FROM brands WHERE name='Scania'), 'Interlink'),
((SELECT id FROM brands WHERE name='Scania'), 'Century'),
((SELECT id FROM brands WHERE name='Scania'), 'K-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'L-Series'),
((SELECT id FROM brands WHERE name='Scania'), 'OmniExpress'),
((SELECT id FROM brands WHERE name='Scania'), 'Tourism'),
((SELECT id FROM brands WHERE name='Scania'), 'Higer'),
((SELECT id FROM brands WHERE name='Scania'), 'Metrolink'),
((SELECT id FROM brands WHERE name='Scania'), 'Fencer'),
((SELECT id FROM brands WHERE name='Scania'), 'Vabis');

-- Seat
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Seat'), 'Ibiza II'),
((SELECT id FROM brands WHERE name='Seat'), 'Leon III'),
((SELECT id FROM brands WHERE name='Seat'), 'Ibiza'),
((SELECT id FROM brands WHERE name='Seat'), 'Leon'),
((SELECT id FROM brands WHERE name='Seat'), 'Toledo'),
((SELECT id FROM brands WHERE name='Seat'), 'Altea'),
((SELECT id FROM brands WHERE name='Seat'), 'Arona'),
((SELECT id FROM brands WHERE name='Seat'), 'Ateca'),
((SELECT id FROM brands WHERE name='Seat'), 'Tarraco'),
((SELECT id FROM brands WHERE name='Seat'), 'Alhambra'),
((SELECT id FROM brands WHERE name='Seat'), 'Mii'),
((SELECT id FROM brands WHERE name='Seat'), 'Exeo'),
((SELECT id FROM brands WHERE name='Seat'), 'Cordoba'),
((SELECT id FROM brands WHERE name='Seat'), 'Inca'),
((SELECT id FROM brands WHERE name='Seat'), 'Terra'),
((SELECT id FROM brands WHERE name='Seat'), 'Malaga'),
((SELECT id FROM brands WHERE name='Seat'), 'Marbella'),
((SELECT id FROM brands WHERE name='Seat'), 'Panda'),
((SELECT id FROM brands WHERE name='Seat'), 'Fura'),
((SELECT id FROM brands WHERE name='Seat'), 'Ronda'),
((SELECT id FROM brands WHERE name='Seat'), '600'),
((SELECT id FROM brands WHERE name='Seat'), '850'),
((SELECT id FROM brands WHERE name='Seat'), '124'),
((SELECT id FROM brands WHERE name='Seat'), '127'),
((SELECT id FROM brands WHERE name='Seat'), '128'),
((SELECT id FROM brands WHERE name='Seat'), '131'),
((SELECT id FROM brands WHERE name='Seat'), '132'),
((SELECT id FROM brands WHERE name='Seat'), '1400'),
((SELECT id FROM brands WHERE name='Seat'), '1500');

-- Setra
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Setra'), 'S 416'),
((SELECT id FROM brands WHERE name='Setra'), 'S 415'),
((SELECT id FROM brands WHERE name='Setra'), 'S 417'),
((SELECT id FROM brands WHERE name='Setra'), 'S 431'),
((SELECT id FROM brands WHERE name='Setra'), 'S 515'),
((SELECT id FROM brands WHERE name='Setra'), 'S 516'),
((SELECT id FROM brands WHERE name='Setra'), 'S 517'),
((SELECT id FROM brands WHERE name='Setra'), 'S 518'),
((SELECT id FROM brands WHERE name='Setra'), 'S 531'),
((SELECT id FROM brands WHERE name='Setra'), 'TopClass S 216'),
((SELECT id FROM brands WHERE name='Setra'), 'TopClass S 217'),
((SELECT id FROM brands WHERE name='Setra'), 'TopClass S 218'),
((SELECT id FROM brands WHERE name='Setra'), 'TopClass S 228'),
((SELECT id FROM brands WHERE name='Setra'), 'ComfortClass S 515'),
((SELECT id FROM brands WHERE name='Setra'), 'ComfortClass S 516'),
((SELECT id FROM brands WHERE name='Setra'), 'ComfortClass S 517'),
((SELECT id FROM brands WHERE name='Setra'), 'MultiClass S 412'),
((SELECT id FROM brands WHERE name='Setra'), 'MultiClass S 415'),
((SELECT id FROM brands WHERE name='Setra'), 'MultiClass S 418'),
((SELECT id FROM brands WHERE name='Setra'), 'MultiClass S 425'),
((SELECT id FROM brands WHERE name='Setra'), 'S 200'),
((SELECT id FROM brands WHERE name='Setra'), 'S 300'),
((SELECT id FROM brands WHERE name='Setra'), 'S 215'),
((SELECT id FROM brands WHERE name='Setra'), 'S 211'),
((SELECT id FROM brands WHERE name='Setra'), 'S 210'),
((SELECT id FROM brands WHERE name='Setra'), 'S 213');

-- SHL
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='SHL'), 'M11'),
((SELECT id FROM brands WHERE name='SHL'), 'M06'),
((SELECT id FROM brands WHERE name='SHL'), 'M04'),
((SELECT id FROM brands WHERE name='SHL'), '175'),
((SELECT id FROM brands WHERE name='SHL'), '250'),
((SELECT id FROM brands WHERE name='SHL'), '350'),
((SELECT id FROM brands WHERE name='SHL'), 'M16'),
((SELECT id FROM brands WHERE name='SHL'), 'S01');

-- Simson
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Simson'), 'S51'),
((SELECT id FROM brands WHERE name='Simson'), 'S50'),
((SELECT id FROM brands WHERE name='Simson'), 'S53'),
((SELECT id FROM brands WHERE name='Simson'), 'S70'),
((SELECT id FROM brands WHERE name='Simson'), 'SR50'),
((SELECT id FROM brands WHERE name='Simson'), 'Star'),
((SELECT id FROM brands WHERE name='Simson'), 'Schwalbe'),
((SELECT id FROM brands WHERE name='Simson'), 'Habicht'),
((SELECT id FROM brands WHERE name='Simson'), 'Sperber'),
((SELECT id FROM brands WHERE name='Simson'), 'Duo'),
((SELECT id FROM brands WHERE name='Simson'), 'Roller'),
((SELECT id FROM brands WHERE name='Simson'), 'Mofa'),
((SELECT id FROM brands WHERE name='Simson'), 'Moped');

-- Skoda
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Skoda'), 'Octavia III'),
((SELECT id FROM brands WHERE name='Skoda'), 'Favorit'),
((SELECT id FROM brands WHERE name='Skoda'), 'Felicia'),
((SELECT id FROM brands WHERE name='Skoda'), 'Fabia III'),
((SELECT id FROM brands WHERE name='Skoda'), 'Octavia'),
((SELECT id FROM brands WHERE name='Skoda'), 'Superb'),
((SELECT id FROM brands WHERE name='Skoda'), 'Kodiaq'),
((SELECT id FROM brands WHERE name='Skoda'), 'Karoq'),
((SELECT id FROM brands WHERE name='Skoda'), 'Scala'),
((SELECT id FROM brands WHERE name='Skoda'), 'Kamiq'),
((SELECT id FROM brands WHERE name='Skoda'), 'Citigo'),
((SELECT id FROM brands WHERE name='Skoda'), 'Roomster'),
((SELECT id FROM brands WHERE name='Skoda'), 'Yeti'),
((SELECT id FROM brands WHERE name='Skoda'), 'Rapid'),
((SELECT id FROM brands WHERE name='Skoda'), 'Enyaq iV'),
((SELECT id FROM brands WHERE name='Skoda'), 'Enyaq Coupe'),
((SELECT id FROM brands WHERE name='Skoda'), '108'),
((SELECT id FROM brands WHERE name='Skoda'), '120'),
((SELECT id FROM brands WHERE name='Skoda'), '125'),
((SELECT id FROM brands WHERE name='Skoda'), '130'),
((SELECT id FROM brands WHERE name='Skoda'), '135'),
((SELECT id FROM brands WHERE name='Skoda'), '136'),
((SELECT id FROM brands WHERE name='Skoda'), 'S 100'),
((SELECT id FROM brands WHERE name='Skoda'), 'S 120'),
((SELECT id FROM brands WHERE name='Skoda'), '1000 MB'),
((SELECT id FROM brands WHERE name='Skoda'), '110 R'),
((SELECT id FROM brands WHERE name='Skoda'), 'Forman'),
((SELECT id FROM brands WHERE name='Skoda'), 'Pickup'),
((SELECT id FROM brands WHERE name='Skoda'), 'Praktik'),
((SELECT id FROM brands WHERE name='Skoda'), 'Octavia II'),
((SELECT id FROM brands WHERE name='Skoda'), 'Octavia I'),
((SELECT id FROM brands WHERE name='Skoda'), 'Fabia I'),
((SELECT id FROM brands WHERE name='Skoda'), 'Fabia II');

-- Smart
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Smart'), 'Fortwo'),
((SELECT id FROM brands WHERE name='Smart'), 'Forfour'),
((SELECT id FROM brands WHERE name='Smart'), 'Roadster'),
((SELECT id FROM brands WHERE name='Smart'), 'Crossblade'),
((SELECT id FROM brands WHERE name='Smart'), 'EQ Fortwo'),
((SELECT id FROM brands WHERE name='Smart'), 'EQ Forfour'),
((SELECT id FROM brands WHERE name='Smart'), '#1'),
((SELECT id FROM brands WHERE name='Smart'), '#3');

-- Solaris
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino 18'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino 12'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino 10'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino 9 LE'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino 8'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino Electric'),
((SELECT id FROM brands WHERE name='Solaris'), 'InterUrbino'),
((SELECT id FROM brands WHERE name='Solaris'), 'Vacanza'),
((SELECT id FROM brands WHERE name='Solaris'), 'Valletta'),
((SELECT id FROM brands WHERE name='Solaris'), 'Oribus'),
((SELECT id FROM brands WHERE name='Solaris'), 'Alpino'),
((SELECT id FROM brands WHERE name='Solaris'), 'Urbino Hybrid'),
((SELECT id FROM brands WHERE name='Solaris'), 'Trollino');

-- Star
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Star'), '266'),
((SELECT id FROM brands WHERE name='Star'), '200'),
((SELECT id FROM brands WHERE name='Star'), '244'),
((SELECT id FROM brands WHERE name='Star'), '1142'),
((SELECT id FROM brands WHERE name='Star'), 'S-42'),
((SELECT id FROM brands WHERE name='Star'), '20'),
((SELECT id FROM brands WHERE name='Star'), '21'),
((SELECT id FROM brands WHERE name='Star'), '25'),
((SELECT id FROM brands WHERE name='Star'), '28'),
((SELECT id FROM brands WHERE name='Star'), '660'),
((SELECT id FROM brands WHERE name='Star'), '742'),
((SELECT id FROM brands WHERE name='Star'), 'N-52');

-- Subaru
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Subaru'), 'Impreza WRX'),
((SELECT id FROM brands WHERE name='Subaru'), 'Impreza'),
((SELECT id FROM brands WHERE name='Subaru'), 'Legacy'),
((SELECT id FROM brands WHERE name='Subaru'), 'Outback'),
((SELECT id FROM brands WHERE name='Subaru'), 'Forester'),
((SELECT id FROM brands WHERE name='Subaru'), 'XV'),
((SELECT id FROM brands WHERE name='Subaru'), 'BRZ'),
((SELECT id FROM brands WHERE name='Subaru'), 'SVX'),
((SELECT id FROM brands WHERE name='Subaru'), 'Justy'),
((SELECT id FROM brands WHERE name='Subaru'), 'Traviq'),
((SELECT id FROM brands WHERE name='Subaru'), 'Baja'),
((SELECT id FROM brands WHERE name='Subaru'), 'Tribeca'),
((SELECT id FROM brands WHERE name='Subaru'), 'WRX'),
((SELECT id FROM brands WHERE name='Subaru'), 'Solterra');

-- Suzuki
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-R750'),
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-R600'),
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-R1000'),
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-S750'),
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-S1000'),
((SELECT id FROM brands WHERE name='Suzuki'), 'RF 900'),
((SELECT id FROM brands WHERE name='Suzuki'), 'SV 650'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Hayabusa'),
((SELECT id FROM brands WHERE name='Suzuki'), 'V-Strom'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Swift'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Vitara'),
((SELECT id FROM brands WHERE name='Suzuki'), 'S-Cross'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Jimny'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Ignis'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Balen'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Splash'),
((SELECT id FROM brands WHERE name='Suzuki'), 'SX4'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Alto'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Celerio'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Wagon R+'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Liana'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Grand Vitara'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Across'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Swace'),
((SELECT id FROM brands WHERE name='Suzuki'), 'DR-Z 400'),
((SELECT id FROM brands WHERE name='Suzuki'), 'RM-Z 450'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Burgman'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Address'),
((SELECT id FROM brands WHERE name='Suzuki'), 'GSX-8S'),
((SELECT id FROM brands WHERE name='Suzuki'), 'Scross');

-- Syrena
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Syrena'), '105'),
((SELECT id FROM brands WHERE name='Syrena'), '101'),
((SELECT id FROM brands WHERE name='Syrena'), '102'),
((SELECT id FROM brands WHERE name='Syrena'), '103'),
((SELECT id FROM brands WHERE name='Syrena'), '104'),
((SELECT id FROM brands WHERE name='Syrena'), 'R-20'),
((SELECT id FROM brands WHERE name='Syrena'), 'Bosto'),
((SELECT id FROM brands WHERE name='Syrena'), 'S-15'),
((SELECT id FROM brands WHERE name='Syrena'), 'Mikrobus'),
((SELECT id FROM brands WHERE name='Syrena'), '104S'),
((SELECT id FROM brands WHERE name='Syrena'), '105L'),
((SELECT id FROM brands WHERE name='Syrena'), '105S');

-- Tatra
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Tatra'), '815'),
((SELECT id FROM brands WHERE name='Tatra'), 'T3'),
((SELECT id FROM brands WHERE name='Tatra'), 'T4'),
((SELECT id FROM brands WHERE name='Tatra'), 'T6'),
((SELECT id FROM brands WHERE name='Tatra'), 'T7'),
((SELECT id FROM brands WHERE name='Tatra'), '148'),
((SELECT id FROM brands WHERE name='Tatra'), '138'),
((SELECT id FROM brands WHERE name='Tatra'), '813'),
((SELECT id FROM brands WHERE name='Tatra'), '603'),
((SELECT id FROM brands WHERE name='Tatra'), '613'),
((SELECT id FROM brands WHERE name='Tatra'), '700'),
((SELECT id FROM brands WHERE name='Tatra'), 'Phoenix'),
((SELECT id FROM brands WHERE name='Tatra'), 'Jamal'),
((SELECT id FROM brands WHERE name='Tatra'), 'T-163'),
((SELECT id FROM brands WHERE name='Tatra'), 'T-810'),
((SELECT id FROM brands WHERE name='Tatra'), 'T-158');

-- Tesla
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Tesla'), 'Model 3'),
((SELECT id FROM brands WHERE name='Tesla'), 'Model S'),
((SELECT id FROM brands WHERE name='Tesla'), 'Model X'),
((SELECT id FROM brands WHERE name='Tesla'), 'Model Y'),
((SELECT id FROM brands WHERE name='Tesla'), 'Roadster'),
((SELECT id FROM brands WHERE name='Tesla'), 'Cybertruck'),
((SELECT id FROM brands WHERE name='Tesla'), 'Semi');

-- Toyota
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Toyota'), 'Corolla E10'),
((SELECT id FROM brands WHERE name='Toyota'), 'Avensis'),
((SELECT id FROM brands WHERE name='Toyota'), 'Camry XV50'),
((SELECT id FROM brands WHERE name='Toyota'), 'Corolla E210'),
((SELECT id FROM brands WHERE name='Toyota'), 'Supra MK4'),
((SELECT id FROM brands WHERE name='Toyota'), 'Celica'),
((SELECT id FROM brands WHERE name='Toyota'), 'Yaris'),
((SELECT id FROM brands WHERE name='Toyota'), 'Aygo'),
((SELECT id FROM brands WHERE name='Toyota'), 'Corolla'),
((SELECT id FROM brands WHERE name='Toyota'), 'Camry'),
((SELECT id FROM brands WHERE name='Toyota'), 'RAV4'),
((SELECT id FROM brands WHERE name='Toyota'), 'Hilux'),
((SELECT id FROM brands WHERE name='Toyota'), 'Land Cruiser'),
((SELECT id FROM brands WHERE name='Toyota'), 'Prius'),
((SELECT id FROM brands WHERE name='Toyota'), 'C-HR'),
((SELECT id FROM brands WHERE name='Toyota'), 'bZ4X'),
((SELECT id FROM brands WHERE name='Toyota'), 'Mirai'),
((SELECT id FROM brands WHERE name='Toyota'), 'GR Supra'),
((SELECT id FROM brands WHERE name='Toyota'), 'GR Yaris'),
((SELECT id FROM brands WHERE name='Toyota'), 'GR86'),
((SELECT id FROM brands WHERE name='Toyota'), 'GT86'),
((SELECT id FROM brands WHERE name='Toyota'), 'Aygo X'),
((SELECT id FROM brands WHERE name='Toyota'), 'Yaris Cross'),
((SELECT id FROM brands WHERE name='Toyota'), 'Highlander'),
((SELECT id FROM brands WHERE name='Toyota'), 'Proace'),
((SELECT id FROM brands WHERE name='Toyota'), 'Proace City'),
((SELECT id FROM brands WHERE name='Toyota'), 'Starlet'),
((SELECT id FROM brands WHERE name='Toyota'), 'Carina'),
((SELECT id FROM brands WHERE name='Toyota'), 'Tercel'),
((SELECT id FROM brands WHERE name='Toyota'), 'Paseo'),
((SELECT id FROM brands WHERE name='Toyota'), 'MR2'),
((SELECT id FROM brands WHERE name='Toyota'), 'Previa'),
((SELECT id FROM brands WHERE name='Toyota'), 'Sienna'),
((SELECT id FROM brands WHERE name='Toyota'), 'Corolla Verso'),
((SELECT id FROM brands WHERE name='Toyota'), 'Urban Cruiser'),
((SELECT id FROM brands WHERE name='Toyota'), 'iQ'),
((SELECT id FROM brands WHERE name='Toyota'), 'Verso'),
((SELECT id FROM brands WHERE name='Toyota'), '4Runner'),
((SELECT id FROM brands WHERE name='Toyota'), 'Tacoma'),
((SELECT id FROM brands WHERE name='Toyota'), 'Tundra'),
((SELECT id FROM brands WHERE name='Toyota'), 'Sequoia');

-- Trabant
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Trabant'), '601'),
((SELECT id FROM brands WHERE name='Trabant'), '500'),
((SELECT id FROM brands WHERE name='Trabant'), '600'),
((SELECT id FROM brands WHERE name='Trabant'), '1.1'),
((SELECT id FROM brands WHERE name='Trabant'), 'P 50'),
((SELECT id FROM brands WHERE name='Trabant'), 'P 60'),
((SELECT id FROM brands WHERE name='Trabant'), 'P 70');

-- Triumph (cars)
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Triumph'), 'Spitfire'),
((SELECT id FROM brands WHERE name='Triumph'), 'TR6'),
((SELECT id FROM brands WHERE name='Triumph'), 'TR7'),
((SELECT id FROM brands WHERE name='Triumph'), 'TR8'),
((SELECT id FROM brands WHERE name='Triumph'), 'Dolomite'),
((SELECT id FROM brands WHERE name='Triumph'), 'Herald'),
((SELECT id FROM brands WHERE name='Triumph'), 'Vitesse'),
((SELECT id FROM brands WHERE name='Triumph'), 'GT6'),
((SELECT id FROM brands WHERE name='Triumph'), 'Stag'),
((SELECT id FROM brands WHERE name='Triumph'), '2000'),
((SELECT id FROM brands WHERE name='Triumph'), '2500'),
((SELECT id FROM brands WHERE name='Triumph'), 'Acclaim'),
((SELECT id FROM brands WHERE name='Triumph'), 'Mayflower'),
((SELECT id FROM brands WHERE name='Triumph'), 'Racing'),
-- Triumph (motorcycles)
((SELECT id FROM brands WHERE name='Triumph'), 'Street Triple'),
((SELECT id FROM brands WHERE name='Triumph'), 'Bonneville'),
((SELECT id FROM brands WHERE name='Triumph'), 'Tiger 800'),
((SELECT id FROM brands WHERE name='Triumph'), 'Tiger 900'),
((SELECT id FROM brands WHERE name='Triumph'), 'Tiger 1200'),
((SELECT id FROM brands WHERE name='Triumph'), 'Speed Triple'),
((SELECT id FROM brands WHERE name='Triumph'), 'Speed Twin'),
((SELECT id FROM brands WHERE name='Triumph'), 'Scrambler 900'),
((SELECT id FROM brands WHERE name='Triumph'), 'Thruxton'),
((SELECT id FROM brands WHERE name='Triumph'), 'Rocket 3'),
((SELECT id FROM brands WHERE name='Triumph'), 'Daytona 675'),
((SELECT id FROM brands WHERE name='Triumph'), 'Street Scrambler'),
((SELECT id FROM brands WHERE name='Triumph'), 'Trident 660'),
((SELECT id FROM brands WHERE name='Triumph'), 'Tiger Sport'),
((SELECT id FROM brands WHERE name='Triumph'), 'Bobber'),
((SELECT id FROM brands WHERE name='Triumph'), 'T100'),
((SELECT id FROM brands WHERE name='Triumph'), 'T120'),
((SELECT id FROM brands WHERE name='Triumph'), 'Speed 400'),
((SELECT id FROM brands WHERE name='Triumph'), 'Scrambler 400 X');

-- Ursus
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Ursus'), 'C-360'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-330'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-350'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-362'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-385'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-4011'),
((SELECT id FROM brands WHERE name='Ursus'), 'C-355'),
((SELECT id FROM brands WHERE name='Ursus'), '512'),
((SELECT id FROM brands WHERE name='Ursus'), '914'),
((SELECT id FROM brands WHERE name='Ursus'), '1012'),
((SELECT id FROM brands WHERE name='Ursus'), '1014'),
((SELECT id FROM brands WHERE name='Ursus'), '1634'),
((SELECT id FROM brands WHERE name='Ursus'), '5314'),
((SELECT id FROM brands WHERE name='Ursus'), '8014'),
((SELECT id FROM brands WHERE name='Ursus'), '9024'),
((SELECT id FROM brands WHERE name='Ursus'), '1204'),
((SELECT id FROM brands WHERE name='Ursus'), '1224'),
((SELECT id FROM brands WHERE name='Ursus'), '1414'),
((SELECT id FROM brands WHERE name='Ursus'), 'Maserati'),
((SELECT id FROM brands WHERE name='Ursus'), 'Neptun'),
((SELECT id FROM brands WHERE name='Ursus'), 'Torpedo'),
((SELECT id FROM brands WHERE name='Ursus'), 'A'),
((SELECT id FROM brands WHERE name='Ursus'), 'K'),
((SELECT id FROM brands WHERE name='Ursus'), 'S');

-- Volkswagen
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Volkswagen'), 'Garbus'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Passat B5'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf VI'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf II'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Polo IV'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Up!'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Passat B8'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Crafter'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf III'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf IV'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf V'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf VII'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Golf VIII'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Passat'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Polo'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Lupo'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Fox'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Beetle'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'New Beetle'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Touran'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Sharan'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Tiguan'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'T-Roc'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'T-Cross'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Taigo'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'ID.3'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'ID.4'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'ID.5'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'ID. Buzz'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Arteon'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'CC'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Eos'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Scirocco'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Corrado'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Phaeton'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Touareg'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Transporter T5'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Transporter T6'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Transporter T7'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Multivan'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Caravelle'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Caddy'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Amarok'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Kaefer'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Typ 3'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Typ 4'),
((SELECT id FROM brands WHERE name='Volkswagen'), '411'),
((SELECT id FROM brands WHERE name='Volkswagen'), '412'),
((SELECT id FROM brands WHERE name='Volkswagen'), '181'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Iltis'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Vento'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Bora'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Jetta'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Santana'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Passat CC'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Routan'),
((SELECT id FROM brands WHERE name='Volkswagen'), 'Viloran');

-- Volvo
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Volvo'), 'FH'),
((SELECT id FROM brands WHERE name='Volvo'), 'F12'),
((SELECT id FROM brands WHERE name='Volvo'), '940'),
((SELECT id FROM brands WHERE name='Volvo'), '740'),
((SELECT id FROM brands WHERE name='Volvo'), '240'),
((SELECT id FROM brands WHERE name='Volvo'), 'S40'),
((SELECT id FROM brands WHERE name='Volvo'), 'S60'),
((SELECT id FROM brands WHERE name='Volvo'), 'S70'),
((SELECT id FROM brands WHERE name='Volvo'), 'S80'),
((SELECT id FROM brands WHERE name='Volvo'), 'S90'),
((SELECT id FROM brands WHERE name='Volvo'), 'V40'),
((SELECT id FROM brands WHERE name='Volvo'), 'V50'),
((SELECT id FROM brands WHERE name='Volvo'), 'V60'),
((SELECT id FROM brands WHERE name='Volvo'), 'V70'),
((SELECT id FROM brands WHERE name='Volvo'), 'V90'),
((SELECT id FROM brands WHERE name='Volvo'), 'XC40'),
((SELECT id FROM brands WHERE name='Volvo'), 'XC60'),
((SELECT id FROM brands WHERE name='Volvo'), 'XC70'),
((SELECT id FROM brands WHERE name='Volvo'), 'XC90'),
((SELECT id FROM brands WHERE name='Volvo'), 'C30'),
((SELECT id FROM brands WHERE name='Volvo'), 'C70'),
((SELECT id FROM brands WHERE name='Volvo'), '850'),
((SELECT id FROM brands WHERE name='Volvo'), '440'),
((SELECT id FROM brands WHERE name='Volvo'), '460'),
((SELECT id FROM brands WHERE name='Volvo'), '480'),
((SELECT id FROM brands WHERE name='Volvo'), '66'),
((SELECT id FROM brands WHERE name='Volvo'), 'Laplander'),
((SELECT id FROM brands WHERE name='Volvo'), '7900'),
((SELECT id FROM brands WHERE name='Volvo'), '7700'),
((SELECT id FROM brands WHERE name='Volvo'), '8700'),
((SELECT id FROM brands WHERE name='Volvo'), '8900'),
((SELECT id FROM brands WHERE name='Volvo'), '9700'),
((SELECT id FROM brands WHERE name='Volvo'), '9900'),
((SELECT id FROM brands WHERE name='Volvo'), 'FH16'),
((SELECT id FROM brands WHERE name='Volvo'), 'FM'),
((SELECT id FROM brands WHERE name='Volvo'), 'FMX'),
((SELECT id FROM brands WHERE name='Volvo'), 'FL'),
((SELECT id FROM brands WHERE name='Volvo'), 'FE'),
((SELECT id FROM brands WHERE name='Volvo'), 'S-Line'),
((SELECT id FROM brands WHERE name='Volvo'), 'C40 Recharge'),
((SELECT id FROM brands WHERE name='Volvo'), 'EX30'),
((SELECT id FROM brands WHERE name='Volvo'), 'EX90'),
((SELECT id FROM brands WHERE name='Volvo'), 'EM90');

-- Wartburg
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Wartburg'), '353'),
((SELECT id FROM brands WHERE name='Wartburg'), '311'),
((SELECT id FROM brands WHERE name='Wartburg'), '312'),
((SELECT id FROM brands WHERE name='Wartburg'), '313'),
((SELECT id FROM brands WHERE name='Wartburg'), '1.3'),
((SELECT id FROM brands WHERE name='Wartburg'), 'Tourist'),
((SELECT id FROM brands WHERE name='Wartburg'), 'Camping'),
((SELECT id FROM brands WHERE name='Wartburg'), 'Melkus'),
((SELECT id FROM brands WHERE name='Wartburg'), '900'),
((SELECT id FROM brands WHERE name='Wartburg'), '1000'),
((SELECT id FROM brands WHERE name='Wartburg'), '1100'),
((SELECT id FROM brands WHERE name='Wartburg'), '1200'),
((SELECT id FROM brands WHERE name='Wartburg'), '1300'),
((SELECT id FROM brands WHERE name='Wartburg'), '1500'),
((SELECT id FROM brands WHERE name='Wartburg'), 'S 100'),
((SELECT id FROM brands WHERE name='Wartburg'), 'S 120'),
((SELECT id FROM brands WHERE name='Wartburg'), 'S 130'),
((SELECT id FROM brands WHERE name='Wartburg'), 'S 150'),
((SELECT id FROM brands WHERE name='Wartburg'), 'New Wartburg');

-- WSK
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='WSK'), '125'),
((SELECT id FROM brands WHERE name='WSK'), '150'),
((SELECT id FROM brands WHERE name='WSK'), '175'),
((SELECT id FROM brands WHERE name='WSK'), '250'),
((SELECT id FROM brands WHERE name='WSK'), 'M06'),
((SELECT id FROM brands WHERE name='WSK'), 'M16'),
((SELECT id FROM brands WHERE name='WSK'), 'S01'),
((SELECT id FROM brands WHERE name='WSK'), 'S03'),
((SELECT id FROM brands WHERE name='WSK'), 'Z-1'),
((SELECT id FROM brands WHERE name='WSK'), 'Z-2'),
((SELECT id FROM brands WHERE name='WSK'), 'M12'),
((SELECT id FROM brands WHERE name='WSK'), 'M21');

-- Yamaha
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Yamaha'), 'YZF-R1'),
((SELECT id FROM brands WHERE name='Yamaha'), 'MT-09'),
((SELECT id FROM brands WHERE name='Yamaha'), 'FZR 600'),
((SELECT id FROM brands WHERE name='Yamaha'), 'YZF-R6'),
((SELECT id FROM brands WHERE name='Yamaha'), 'MT-07'),
((SELECT id FROM brands WHERE name='Yamaha'), 'MT-10'),
((SELECT id FROM brands WHERE name='Yamaha'), 'XSR 700'),
((SELECT id FROM brands WHERE name='Yamaha'), 'XSR 900'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Tracer 700'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Tracer 900'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Tenere 700'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Super Tenere'),
((SELECT id FROM brands WHERE name='Yamaha'), 'XV 950'),
((SELECT id FROM brands WHERE name='Yamaha'), 'VMAX'),
((SELECT id FROM brands WHERE name='Yamaha'), 'FJR 1300'),
((SELECT id FROM brands WHERE name='Yamaha'), 'XT 660'),
((SELECT id FROM brands WHERE name='Yamaha'), 'WR 450'),
((SELECT id FROM brands WHERE name='Yamaha'), 'YZ 250'),
((SELECT id FROM brands WHERE name='Yamaha'), 'YZ 450'),
((SELECT id FROM brands WHERE name='Yamaha'), 'TMAX'),
((SELECT id FROM brands WHERE name='Yamaha'), 'XMAX'),
((SELECT id FROM brands WHERE name='Yamaha'), 'NMAX'),
((SELECT id FROM brands WHERE name='Yamaha'), 'YP 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'YS 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'SR 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'SR 400'),
((SELECT id FROM brands WHERE name='Yamaha'), 'SR 500'),
((SELECT id FROM brands WHERE name='Yamaha'), 'TW 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'DT 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'RD 125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'RD 350'),
((SELECT id FROM brands WHERE name='Yamaha'), 'RX 100'),
((SELECT id FROM brands WHERE name='Yamaha'), 'RX 135'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R1M'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R6'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R7'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R3'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'MT-125'),
((SELECT id FROM brands WHERE name='Yamaha'), 'MT-03'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Bolt'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Star'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Road Star'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Royal Star'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Raider'),
((SELECT id FROM brands WHERE name='Yamaha'), 'V Star'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Venture'),
((SELECT id FROM brands WHERE name='Yamaha'), 'R-NEO'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Tricity'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Niken'),
((SELECT id FROM brands WHERE name='Yamaha'), 'Yard Built');

-- Zastava
INSERT IGNORE INTO models (brand_id, name) VALUES
((SELECT id FROM brands WHERE name='Zastava'), 'Yugo'),
((SELECT id FROM brands WHERE name='Zastava'), '101'),
((SELECT id FROM brands WHERE name='Zastava'), '110'),
((SELECT id FROM brands WHERE name='Zastava'), '125'),
((SELECT id FROM brands WHERE name='Zastava'), '130'),
((SELECT id FROM brands WHERE name='Zastava'), '150'),
((SELECT id FROM brands WHERE name='Zastava'), '750'),
((SELECT id FROM brands WHERE name='Zastava'), '850'),
((SELECT id FROM brands WHERE name='Zastava'), 'Florida'),
((SELECT id FROM brands WHERE name='Zastava'), 'Nova'),
((SELECT id FROM brands WHERE name='Zastava'), 'GTL'),
((SELECT id FROM brands WHERE name='Zastava'), 'ZLC'),
((SELECT id FROM brands WHERE name='Zastava'), 'Skala'),
((SELECT id FROM brands WHERE name='Zastava'), 'Koral'),
((SELECT id FROM brands WHERE name='Zastava'), 'Ina');
